# Auto-generated by Jules forterraform-enterprise-data team
# Based on tests in internal/configs/configload/copy_dir_test.go

Feature: Directory Copying with Symlink Handling

  This feature describes the behavior of the `copyDir` function, specifically
  how it handles symbolic links when copying a source directory to a target
  directory. This is relevant for processes like fetching modules that may
  contain symlinks.

  Scenario: Copying a directory containing a symbolic link to another directory (submodule)
    Given a source directory "source_dir" with the following structure:
      - "source_dir/actual_module/" (directory)
      - "source_dir/actual_module/main.tf" (file with content "hello")
      - "source_dir/linked_module" (symlink pointing to "actual_module")
    And a target directory "target_dir" exists and is empty
    When "source_dir" is copied to "target_dir" using `copyDir`
    Then the "target_dir" should contain a directory "actual_module"
    And "target_dir/actual_module/main.tf" should exist and contain "hello"
    And the "target_dir" should contain an entry "linked_module"
    And "target_dir/linked_module" should be a symbolic link (or its contents copied, depending on exact copyDir behavior)
    And "target_dir/linked_module/main.tf" should exist (either as part of the copied symlink's target or a direct copy) and contain "hello"
    And the copy operation should complete without errors.
    # Note: The Go test checks for os.Lstat on "target/symlink-module/main.tf",
    # implying that the symlink is preserved and its target's content is accessible via the symlink path.

  Scenario: Copying a directory containing a symbolic link to a file
    Given a source directory "source_dir_file_link" with the following structure:
      - "source_dir_file_link/actual_file.tf" (file with content "world")
      - "source_dir_file_link/linked_file.tf" (symlink pointing to "actual_file.tf")
    And a target directory "target_dir_file_link" exists and is empty
    When "source_dir_file_link" is copied to "target_dir_file_link" using `copyDir`
    Then the "target_dir_file_link" should contain a file "actual_file.tf" with content "world"
    And the "target_dir_file_link" should contain an entry "linked_file.tf"
    And "target_dir_file_link/linked_file.tf" should be a symbolic link to "actual_file.tf" (or a direct copy of "actual_file.tf" with content "world")
    And the copy operation should complete without errors.

  Scenario: Copying an empty directory
    Given a source directory "empty_source_dir" which is empty
    And a target directory "empty_target_dir" exists and is empty
    When "empty_source_dir" is copied to "empty_target_dir" using `copyDir`
    Then the "empty_target_dir" should remain empty (or reflect an empty directory structure)
    And the copy operation should complete without errors.

  Scenario: Copying a directory with nested subdirectories (no symlinks)
    Given a source directory "nested_source_dir" with structure:
      - "nested_source_dir/file1.txt"
      - "nested_source_dir/sub1/"
      - "nested_source_dir/sub1/file2.txt"
      - "nested_source_dir/sub1/sub2/"
      - "nested_source_dir/sub1/sub2/file3.txt"
    And a target directory "nested_target_dir" exists and is empty
    When "nested_source_dir" is copied to "nested_target_dir" using `copyDir`
    Then "nested_target_dir/file1.txt" should exist
    And "nested_target_dir/sub1/file2.txt" should exist
    And "nested_target_dir/sub1/sub2/file3.txt" should exist
    And the copy operation should complete without errors.

  Scenario: Source directory does not exist
    Given a source directory path "non_existent_source_dir" that does not exist
    And a target directory "target_for_non_existent" exists
    When an attempt is made to copy "non_existent_source_dir" to "target_for_non_existent" using `copyDir`
    Then the copy operation should fail with an error indicating the source directory does not exist or cannot be read.
```
