# Auto-generated by Jules forterraform-enterprise-data team
# Based on logic in internal/configs/configload/loader_load.go (moduleWalkerLoad)

Feature: Configuration Loader - Validation Against Module Manifest During Load

  This feature describes how the `Loader.LoadConfig` process (specifically its
  internal module walker) validates module calls in the configuration against
  the existing module manifest (e.g., ".terraform/modules/modules.json") when
  loading already installed modules.

  Background:
    Given a Terraform project with a root module "root.tf"
    And a module manifest file ".terraform/modules/modules.json" exists
    And the Loader is configured to use ".terraform/modules/" as the ModulesDir

  Scenario: Module called in configuration is not listed in the manifest
    Given "root.tf" contains:
      """
      module "unlisted_child" {
        source = "./unlisted_child_dir" # Path doesn't matter as much as manifest lookup
      }
      """
    And the module manifest "modules.json" is empty or does not contain an entry for module path "unlisted_child"
    When the loader attempts to load the configuration from the root directory
    Then a diagnostic error should be reported with summary "Module not installed"
    And its detail should state 'This module is not yet installed. Run "terraform init" to install all modules required by this configuration.'
    And the error subject should point to the `module "unlisted_child"` block in "root.tf".

  Scenario: Module source address in configuration differs from manifest record
    Given "root.tf" contains:
      """
      module "source_changed_child" {
        source = "github.com/example/new_source" # New source in config
      }
      """
    And the module manifest "modules.json" contains an entry for module path "source_changed_child" with:
      - SourceAddr: "github.com/example/old_source"
      - Dir: "./.terraform/modules/source_changed_child_dir" # Valid directory
    And module "./.terraform/modules/source_changed_child_dir/" exists with valid config
    When the loader attempts to load the configuration from the root directory
    Then a diagnostic error should be reported with summary "Module source has changed"
    And its detail should state "The source address was changed since this module was installed. Run \"terraform init\"..."
    And the error subject should point to the `source = "github.com/example/new_source"` line in "root.tf".

  Scenario: Module version constraint in configuration is incompatible with installed version in manifest
    Given "root.tf" contains:
      """
      module "version_mismatch_child" {
        source  = "example.com/org/mod"
        version = "~> 2.0" # Config requires v2.x
      }
      """
    And the module manifest "modules.json" contains an entry for module path "version_mismatch_child" with:
      - SourceAddr: "example.com/org/mod"
      - Version: "1.5.0" # Manifest shows v1.5.0 installed
      - Dir: "./.terraform/modules/version_mismatch_child_dir" # Valid directory
    And module "./.terraform/modules/version_mismatch_child_dir/" exists with valid config
    When the loader attempts to load the configuration from the root directory
    Then a diagnostic error should be reported with summary "Module version requirements have changed"
    And its detail should state 'The version requirements have changed since this module was installed and the installed version (1.5.0) is no longer acceptable.'
    And the error subject should point to the module call in "root.tf".

  Scenario: Module version constraint added in configuration, but manifest shows no version for installed module
    Given "root.tf" contains:
      """
      module "now_versioned_child" {
        source  = "example.com/org/mod"
        version = "~> 1.0" # Config now requires a version
      }
      """
    And the module manifest "modules.json" contains an entry for module path "now_versioned_child" with:
      - SourceAddr: "example.com/org/mod"
      - Version: null # Manifest shows module installed without a specific version
      - Dir: "./.terraform/modules/now_versioned_child_dir" # Valid directory
    And module "./.terraform/modules/now_versioned_child_dir/" exists with valid config
    When the loader attempts to load the configuration from the root directory
    Then a diagnostic error should be reported with summary "Module version requirements have changed"
    And its detail should state "The version requirements have changed since this module was installed and the installed version is no longer acceptable." (or similar, as null version fails check)
    And the error subject should point to the module call in "root.tf".

  Scenario: Installed module directory (from manifest) is missing or unreadable
    Given "root.tf" contains:
      """
      module "missing_dir_child" {
        source  = "example.com/org/mod"
        version = "~> 1.0"
      }
      """
    And the module manifest "modules.json" contains an entry for module path "missing_dir_child" with:
      - SourceAddr: "example.com/org/mod"
      - Version: "1.0.0"
      - Dir: "./.terraform/modules/deleted_child_dir" # This directory does not exist or is unreadable
    When the loader attempts to load the configuration from the root directory
    Then a diagnostic error should be reported with summary "Module not installed"
    And its detail should state 'This module\'s local cache directory ./.terraform/modules/deleted_child_dir could not be read. Run "terraform init"...'
    And the error subject should point to the `module "missing_dir_child"` block in "root.tf".
```
