# Auto-generated by Jules forterraform-enterprise-data team
# Based on tests in internal/configs/configload/loader_snapshot_test.go

Feature: Configuration Loader - Snapshot Creation and Usage

  This feature describes how the Terraform configuration loader creates
  in-memory snapshots of a configuration (including module sources) and
  how it can reconstruct a configuration from such a snapshot. This is
  important for performance and for operations on a "frozen" configuration.

  Background:
    Given a Terraform project with a root module and potentially child modules
    And the project has been initialized (e.g., `terraform init` has run), so child modules are available (e.g., in ".terraform/modules/")

  Scenario: Successfully creating a snapshot of a multi-module configuration
    Given the project "my_project/" has a root module "root.tf":
      """
      module "child_a" { source = "example.com/org/child_a/sys" } # Assumed installed
      module "child_b" { source = "./local_child_b" }
      """
    And module "my_project/.terraform/modules/child_a_src/" (representing installed "example.com/org/child_a/sys") with "child_a.tf":
      """
      output "a_out" { value = "from child A" }
      """
    And module "my_project/local_child_b/" with "child_b.tf":
      """
      output "b_out" { value = "from local child B" }
      """
    And a modules manifest (e.json, ".terraform/modules/modules.json") correctly maps "child_a" to "./.terraform/modules/child_a_src/" and "child_b" to "./local_child_b/"
    When the loader calls `LoadConfigWithSnapshot` for "my_project/"
    Then a Snapshot object should be successfully created without errors
    And the Snapshot should contain module entries for path "" (root), "child_a", and "child_b"
    And the SnapshotModule for path "" should have Dir "my_project/" and its Files map should contain the content of "root.tf"
    And the SnapshotModule for path "child_a" should have Dir "my_project/.terraform/modules/child_a_src/" (or its resolved absolute path)
    And the SnapshotModule for path "child_b" should have Dir "my_project/local_child_b/" (or its resolved absolute path)

  Scenario: Successfully loading a configuration from a snapshot
    Given a valid Snapshot object was created from "my_project/" as described in the "Successfully creating a snapshot" scenario
    And a new loader is created using `NewLoaderFromSnapshot` with this snapshot
    When this new loader calls `LoadConfig` for "my_project/" (the original root path)
    Then a complete Config object should be returned without errors
    And the Config tree should contain modules: "", "child_a", "child_b"
    And the module "child_a" should have SourceDir pointing to "my_project/.terraform/modules/child_a_src/"
    And the output "a_out" from module "child_a" should have value "from child A"
    And the output "b_out" from module "child_b" should have value "from local child B"

  Scenario: Attempting to create a snapshot when a module source is invalid or missing
    Given a project "broken_project/" with "root.tf":
      """
      module "missing_mod" { source = "./non_existent_child" }
      """
    And the directory "broken_project/non_existent_child/" does not exist
    And the modules manifest (if any) might be inconsistent or reflect this missing module
    When the loader calls `LoadConfigWithSnapshot` for "broken_project/"
    Then diagnostics should be reported indicating an error loading module "missing_mod"
    # The exact error could be "could not be found", "no files found", or similar depending on loader stage.
    And the returned Snapshot might be nil or incomplete.

  Scenario: Attempting to create a snapshot when a previously installed module path in manifest is now empty/corrupt
    Given a project "corrupt_install/" with "root.tf":
      """
      module "downloaded_mod" { source = "registry.terraform.io/hashicorp/consul/aws" version = "0.10.0" }
      """
    And the modules manifest exists and lists "downloaded_mod" with a Dir pointing to ".terraform/modules/downloaded_mod_dir"
    But the directory ".terraform/modules/downloaded_mod_dir/" is now empty or contains no .tf files
    When the loader calls `LoadConfigWithSnapshot` for "corrupt_install/"
    Then diagnostics should be reported indicating an error loading module "downloaded_mod"
    And its detail should mention issues like "No configuration files found" or "Unreadable module directory" for the path ".terraform/modules/downloaded_mod_dir/".
```
