# Auto-generated by Jules forterraform-enterprise-data team
# Based on logic in internal/configs/configload/loader.go

Feature: Configuration Loader Initialization and Manifest Handling

  This feature describes the initialization of the Terraform configuration
  Loader (`NewLoader`) and its interaction with the module manifest file
  (e.g., ".terraform/modules/modules.json").

  Scenario: Successful loader initialization with a valid module manifest
    Given a directory ".terraform/modules/" exists
    And ".terraform/modules/modules.json" exists and contains a valid, empty module manifest:
      """
      {
        "Modules": []
      }
      """
    When a new Loader is created with ModulesDir ".terraform/modules/"
    Then the Loader should be initialized successfully without errors
    And its internal module manifest should reflect an empty set of installed modules.

  Scenario: Successful loader initialization with a populated module manifest
    Given a directory ".terraform/modules/" exists
    And ".terraform/modules/modules.json" exists and contains:
      """
      {
        "Modules": [
          {
            "Key": "my_module",
            "Source": "example.com/ns/name/sys",
            "Version": "1.0.0",
            "Dir": "./my_module_dir"
          }
        ]
      }
      """
    When a new Loader is created with ModulesDir ".terraform/modules/"
    Then the Loader should be initialized successfully without errors
    And its internal module manifest should reflect one installed module "my_module".

  Scenario: Loader initialization fails due to corrupted module manifest
    Given a directory ".terraform/modules/" exists
    And ".terraform/modules/modules.json" exists but contains invalid JSON (e.g., "corrupted_content")
    When a new Loader is created with ModulesDir ".terraform/modules/"
    Then an error "failed to read module manifest" should be reported during loader initialization.

  Scenario: Loader initialization with a non-existent module manifest file (graceful handling)
    Given a directory ".terraform/modules/" exists
    But ".terraform/modules/modules.json" does NOT exist
    When a new Loader is created with ModulesDir ".terraform/modules/"
    Then the Loader should be initialized successfully without errors
    And its internal module manifest should be empty (as if no modules are installed).

  Scenario: Refreshing modules updates the loader's manifest view
    Given a Loader is successfully initialized with ModulesDir ".terraform/modules/" and an initially empty "modules.json"
    And the file ".terraform/modules/modules.json" is then updated externally to contain:
      """
      {
        "Modules": [ { "Key": "new_mod", "Source": "s", "Version": "1", "Dir": "./nm" } ]
      }
      """
    When `RefreshModules()` is called on the loader
    Then the loader's internal module manifest should now reflect one installed module "new_mod"
    And `RefreshModules()` should complete without errors.

  Scenario: Importing sources from a snapshot into a loader
    Given a Snapshot object "snap" containing:
      - Module path "" (root) with Dir "project_root/" and File "main.tf" (content: `variable "a" {}`)
      - Module path "child" with Dir "project_root/.tfm/child_dir/" and File "child.tf" (content: `variable "b" {}`)
    And a Loader "main_loader" is initialized
    When `ImportSourcesFromSnapshot(snap)` is called on "main_loader"
    Then the "main_loader"'s parser source cache should contain "project_root/main.tf"
    And the "main_loader"'s parser source cache should contain "project_root/.tfm/child_dir/child.tf"
    # Verification: if a diagnostic later refers to these files, it can show snippets.
```
