# Auto-generated by Jules forterraform-enterprise-data team
# Based on tests in internal/configs/configload/loader_load_test.go

Feature: Configuration Loader - Loading Full Configuration Tree

  This feature describes the behavior of the `Loader.LoadConfig` method,
  which is responsible for loading the root module and all its descendant
  child modules, constructing a complete `configs.Config` tree, and performing
  validations related to module versions and provider configurations.

  Background:
    Given a Terraform project structure with a root module
    And potentially child modules (local or pre-installed in ".terraform/modules/")

  Scenario: Successfully loading a valid multi-module configuration with nested children
    Given the project has a root module "root/" with "root.tf":
      """
      module "child_a" { source = "./child_a" }
      module "child_b" { source = "./child_b" }
      """
    And a child module "root/child_a/" with "child_a.tf":
      """
      module "child_c" { source = "./child_c" }
      output "a_out" { value = "from A" }
      """
    And a child module "root/child_a/child_c/" with "child_c.tf":
      """
      output "c_out" { value = "from C" }
      """
    And a child module "root/child_b/" with "child_b.tf":
      """
      module "child_d" { source = "./child_d" }
      output "b_out" { value = "from B" }
      """
    And a child module "root/child_b/child_d/" with "child_d.tf":
      """
      output "d_out" { value = "from D" }
      """
    When the loader loads the configuration from "root/"
    Then a complete Config object should be returned without critical errors
    And the Config tree should contain modules: "", "child_a", "child_a.child_c", "child_b", "child_b.child_d"
    And the output "c_out" from module "child_a.child_c" should have value "from C"
    And the output "d_out" from module "child_b.child_d" should have value "from D"

  Scenario: Adding a version constraint to a previously unconstrained module call
    Given a project "version_change/" with "root.tf":
      """
      module "local_mod" {
        source  = "./local_mod"
        version = "~> 1.0" # This line was conceptually "added"
      }
      """
    And module "version_change/local_mod/" exists (content doesn't matter for this test)
    And the module installation snapshot (e.g., in ".terraform/modules/modules.json") reflects "local_mod" as installed without a version constraint previously
    When the loader attempts to load the configuration from "version_change/"
    Then a diagnostic error should be reported
    And its summary or detail should contain "Module version requirements have changed" (or similar indicating init is required).

  Scenario: Loading a configuration with parsing errors in the root module
    Given a project "invalid_root/" with "root.tf":
      """
      resource "aws_instance" "my server" { # Invalid name
        ami = "ami-123"
      }
      """
    When the loader loads the configuration from "invalid_root/"
    Then diagnostics should be reported for the invalid resource name
    And a partial Config object should still be returned (not nil)
    And the returned Config's root Module object should not be nil.

  Scenario: Loading a configuration with parsing errors in a child module
    Given a project "invalid_child/" with "root.tf":
      """
      module "broken_child" { source = "./broken_child" }
      """
    And module "invalid_child/broken_child/" with "child.tf":
      """
      variable "input var" { # Invalid name
        type = string
      }
      """
    When the loader loads the configuration from "invalid_child/"
    Then diagnostics should be reported for the invalid variable name in "child.tf"
    And a partial Config object should still be returned (not nil).

  Scenario: Valid use of `count` on a grandchild module when intermediate child has a provider block
    # Regression test for https://github.com/hashicorp/terraform/issues/31081
    Given a project "valid_grandchild_count/" with "root.tf":
      """
      module "intermediate_child" { source = "./intermediate_child" }
      """
    And module "valid_grandchild_count/intermediate_child/" with "child.tf":
      """
      provider "null" {} # Child has its own provider block
      module "counted_grandchild" {
        source = "./grandchild"
        count  = 2 # This is valid as 'counted_grandchild' doesn't have a provider block
      }
      """
    And module "valid_grandchild_count/intermediate_child/grandchild/" with "grandchild.tf":
      """
      # No provider block here
      resource "null_resource" "example" {}
      """
    When the loader loads the configuration from "valid_grandchild_count/"
    Then the configuration should load successfully without "Module is incompatible with count" errors for "counted_grandchild".

  Scenario: Invalid use of `count` on a child module that itself contains a provider block
    Given a project "invalid_child_count/" with "root.tf":
      """
      module "child_with_provider_and_count" {
        source = "./child"
        count  = 2 # Invalid because child.tf has a provider block
      }
      """
    And module "invalid_child_count/child/" with "child.tf":
      """
      provider "null" {} # Child has its own provider block
      resource "null_resource" "example" {}
      """
    When the loader loads the configuration from "invalid_child_count/"
    Then a diagnostic error should be reported
    And its summary should contain "Module is incompatible with count, for_each, and depends_on"
    And its detail should reference "module.child_with_provider_and_count".
```
