# Auto-generated by Jules forterraform-enterprise-data team
# Based on logic in internal/configs/action.go

Feature: Parsing `action` and `action_trigger` Blocks

  This feature describes how Terraform parses `action` blocks and
  `action_trigger` blocks (within resource lifecycles), including
  validation of their attributes, labels, and references.

  Scenario Outline: Valid `action` block definition
    Given a configuration file with an `action` block defined as:
      """
      action "<action_type>" "<action_name>" {
        <attributes>
      }
      """
    When the configuration is parsed
    Then an action with type "<action_type>" and name "<action_name>" should be successfully parsed
    And if "<expected_provider_local_name>" is not empty, its implied provider local name should be "<expected_provider_local_name>"
    And if "<explicit_provider_ref>" is not empty, its explicit provider reference should be "<explicit_provider_ref>"
    And if "<count_expr>" is not empty, its count expression should be "<count_expr>"
    And if "<for_each_expr>" is not empty, its for_each expression should be "<for_each_expr>"
    And if "<depends_on_refs>" is not empty, its depends_on references should include <depends_on_refs>
    And no critical parsing diagnostics should be reported for this action block

    Examples:
      | action_type | action_name | attributes                                      | expected_provider_local_name | explicit_provider_ref | count_expr | for_each_expr | depends_on_refs        |
      | http        | call_api    | # No extra attributes                           | http                         |                       |            |               |                        |
      | custom      | my_task     | provider = custom.special\n  count = 2          | custom                       | custom.special        | 2          |               |                        |
      | local-exec  | run_script  | for_each = toset(["a", "b"])\n depends_on = [aws_instance.foo] | local-exec                   |                       |            | toset(["a", "b"]) | ["aws_instance.foo"]   |
      | service-x   | do_thing    | # empty body                                    | service-x                    |                       |            |               |                        |

  Scenario Outline: Invalid `action` block definitions
    Given a configuration file with an `action` block defined as:
      """
      <action_block_hcl>
      """
    When the configuration is parsed
    Then a diagnostic error with summary "<expected_error_summary>" should be reported
    And if "<expected_error_detail_fragment>" is not empty, the error detail should contain "<expected_error_detail_fragment>"

    Examples:
      | action_block_hcl                                 | expected_error_summary                 | expected_error_detail_fragment |
      | action "http" "123invalid" {}                    | Invalid action name                    | must be a valid identifier     |
      | action "http invalid" "validname" {}             | Invalid action type name                 | must be a valid identifier     |
      | action http {}                                   | Missing action name                    | (parser-level error)           | # Expecting 2 labels
      | action {}                                        | Missing action type                    | (parser-level error)           | # Expecting 2 labels
      | action "http" "name" { count=1, for_each=var.x } | Invalid combination of "count" and "for_each" | mutually-exclusive             |

  Scenario Outline: Valid `action_trigger` block definition within a resource lifecycle
    Given a configuration file with a resource "null_resource" "example" containing a lifecycle block with an `action_trigger` defined as:
      """
      action_trigger {
        <attributes>
      }
      """
    And an action block `action "email" "notify_admin" {}` is also defined
    When the configuration is parsed
    Then the "null_resource" "example" should have a valid action_trigger
    And its condition expression should be "<condition_expr>" if "<condition_expr>" is not empty
    And its events should be <expected_events>
    And its action references should include <expected_action_refs>
    And no critical parsing diagnostics should be reported for this action_trigger block

    Examples:
      | attributes                                                                 | condition_expr   | expected_events                                 | expected_action_refs             |
      | events = [before_create, after_destroy]\n actions = [action.email.notify_admin] |                  | ["before_create", "after_destroy"]              | ["action.email.notify_admin"]    |
      | condition = self.id != null\n events = [after_update]\n actions = [action.email.notify_admin] | self.id != null  | ["after_update"]                                | ["action.email.notify_admin"]    |
      | events = [before_update]\n actions = [action.email.notify_admin]         |                  | ["before_update"]                               | ["action.email.notify_admin"]    |

  Scenario Outline: Invalid `action_trigger` block definitions
    Given a configuration file with a resource "null_resource" "example" containing a lifecycle block with an `action_trigger` defined as:
      """
      action_trigger {
        <attributes>
      }
      """
    And an action block `action "email" "notify_admin" {}` is also defined
    When the configuration is parsed
    Then a diagnostic error with summary "<expected_error_summary>" should be reported for the action_trigger
    And if "<expected_error_detail_fragment>" is not empty, the error detail should contain "<expected_error_detail_fragment>"

    Examples:
      | attributes                                                                 | expected_error_summary                 | expected_error_detail_fragment     |
      | actions = [action.email.notify_admin]                                      | Missing required argument              | events                             | # Missing events
      | events = [before_create]                                                   | Missing required argument              | actions                            | # Missing actions
      | events = [before_create, invalid_event]\n actions = [action.email.notify_admin] | Invalid "event" value invalid_event    | supports the following values      |
      | events = []\n actions = [action.email.notify_admin]                        | No events specified                    | At least one event must be specified |
      | events = [after_create]\n actions = []                                     | No actions specified                   | At least one action must be specified|
      | events = [after_create]\n actions = [aws_instance.foo]                     | Invalid actions argument inside action_triggers | accepts a list of one or more actions | # Referencing a non-action
```
