# Auto-generated by Jules forterraform-enterprise-data team
# Based on logic in internal/configs/checks.go

Feature: Parsing `check` Blocks and General Check Rule Validation

  This feature describes how Terraform parses top-level `check` blocks and
  validates general rules for `CheckRule` constructs (like those used in
  variable validation, resource/data preconditions/postconditions, and
  `check` block asserts).

  Scenario: Valid `check` block definition
    Given a configuration file with the following content:
      """
      data "external" "example" {
        program = ["echo", "{\"name\":\"example\"}"]
      }

      check "example_check" {
        data "external" "checker" {
          program = ["echo", "{\"status\":\"ok\"}"]
        }

        assert {
          condition     = data.external.checker.result.status == "ok" && data.external.example.result.name != ""
          error_message = "Checker status was not ok or example name was empty."
        }

        assert {
          condition     = length(data.external.example.result.name) > 0
          error_message = "Example name must not be empty."
        }
      }
      """
    When the configuration is parsed
    Then a check block named "example_check" should be successfully parsed
    And it should contain one data block of type "external" named "checker"
    And it should contain 2 assert blocks
    And the first assert block's condition should be 'data.external.checker.result.status == "ok" && data.external.example.result.name != ""'
    And its error_message should be "Checker status was not ok or example name was empty."
    And no critical parsing diagnostics should be reported for this check block

  Scenario: `check` block with only assert blocks (no data block)
    Given a configuration file with the following content:
      """
      variable "input" {
        type    = string
        default = "valid"
      }

      check "assert_only_check" {
        assert {
          condition     = var.input == "valid"
          error_message = "Input must be 'valid'."
        }
      }
      """
    When the configuration is parsed
    Then a check block named "assert_only_check" should be successfully parsed
    And it should contain zero data blocks
    And it should contain 1 assert block
    And no critical parsing diagnostics should be reported

  Scenario Outline: Invalid `check` block definitions
    Given a configuration file with a `check` block defined as:
      """
      <check_block_hcl>
      """
    When the configuration is parsed
    Then a diagnostic error with summary "<expected_error_summary>" should be reported
    And if "<expected_error_detail_fragment>" is not empty, the error detail should contain "<expected_error_detail_fragment>"

    Examples:
      | check_block_hcl                                                                 | expected_error_summary                 | expected_error_detail_fragment   |
      | check "123invalid" {}                                                           | Invalid check block name               | must be a valid identifier       |
      | check {}                                                                        | Missing check block name               | (parser-level error)             |
      | check "too_many_data" { data "foo" "bar" {} \n data "baz" "qux" {} \n assert { condition = true, error_message = "m" } } | Multiple data resource blocks        | already has a data resource defined |
      | check "no_asserts" { data "foo" "bar" {} }                                      | Zero assert blocks                     | must have at least one assert    |
      | check "bad_assert" { assert {} }                                                | Missing required argument              | condition                        | # Missing condition in assert
      | check "bad_assert2" { assert { condition = true } }                             | Missing required argument              | error_message                    | # Missing error_message in assert

  Scenario Outline: General `CheckRule` validation (applies to variable validation, pre/postconditions, check asserts)
    Given a configuration file containing a block type "<block_type>" (e.g., variable, resource) with a check rule (e.g. validation, precondition, assert) defined as:
      """
      <check_rule_hcl>
      """
    When the configuration is parsed
    Then a diagnostic error with summary "<expected_error_summary>" should be reported for the check rule
    And its detail should contain "<expected_error_detail_fragment>"

    Examples:
      | block_type | check_rule_hcl                                              | expected_error_summary     | expected_error_detail_fragment                               |
      | resource   | resource "null_resource" "test" { precondition { condition = true, error_message = "msg" } } | Invalid precondition expression | The condition expression must refer to at least one object | # Static condition
      | variable   | variable "test" { type = string validation { condition = "static", error_message = "msg" } } | Invalid validation expression   | The condition expression must refer to at least one object | # Static condition
      | check      | check "my_check" { assert { condition = (1==1), error_message = "msg" } } | Invalid assert expression     | The condition expression must refer to at least one object | # Static condition

  Scenario: Attempting to override a `check` block
    Given a directory "override_check_module" with a file "main.tf" containing:
      """
      check "my_check" {
        assert {
          condition = var.foo == "bar"
          error_message = "Foo must be bar."
        }
      }
      variable "foo" { type = string }
      """
    And the same directory also has a file "override.tf" containing:
      """
      check "my_check" {
        assert {
          condition = var.foo == "baz" # Attempt to change condition
          error_message = "Foo must be baz."
        }
      }
      """
    When the parser loads the configuration directory "override_check_module"
    Then a diagnostic error with summary "Can't override check blocks" should be reported
    And its detail should contain "Override files cannot override check blocks."

  Scenario: Attempting to override a `precondition` block within a resource
    Given a directory "override_precond_module" with a file "main.tf" containing:
      """
      resource "null_resource" "test" {
        precondition {
          condition = var.foo == "bar"
          error_message = "Original."
        }
      }
      variable "foo" { type = string }
      """
    And the same directory also has a file "override.tf" containing:
      """
      resource "null_resource" "test" {
        precondition {
          condition = var.foo == "baz"
          error_message = "Overridden."
        }
      }
      """
    When the parser loads the configuration directory "override_precond_module"
    Then a diagnostic error with summary "Can't override precondition blocks" should be reported
    And its detail should contain "Override files cannot override \"precondition\" blocks."

  Scenario: Resource precondition self-referencing (invalid)
    Given a configuration file with:
      """
      resource "aws_instance" "web" {
        ami           = "ami-123"
        instance_type = "t2.micro"

        precondition {
          condition     = self.id != null # Invalid: self reference in precondition
          error_message = "Instance ID should not be null (which it always is here)."
        }
      }
      """
    When the configuration is parsed
    Then a diagnostic error with summary "Invalid reference in precondition" should be reported for resource "aws_instance.web"
    And its detail should contain "Configuration for aws_instance.web may not refer to itself."
```
