# Auto-generated by Jules forterraform-enterprise-data team
# Based on logic in internal/configs/compat_shim.go
# and test files in internal/configs/testdata/warning-files/

Feature: Configuration Compatibility Shims for Deprecated Syntax

  This feature describes how Terraform handles certain deprecated syntax patterns
  to maintain backward compatibility, while issuing warnings to guide users
  towards modern syntax.

  Scenario: Quoted reference in `depends_on` attribute
    Given a configuration file containing:
      """
      resource "null_resource" "a" {
      }

      resource "null_resource" "b" {
        depends_on = ["null_resource.a"] # Quoted reference
      }
      """
    When the configuration is parsed
    Then the resource "null_resource" "b" should correctly depend on "null_resource" "a"
    And a warning diagnostic should be reported with:
      | Summary                        | Detail Contain                                                                                                                                                                      | Line |
      | Quoted references are deprecated | In this context, references are expected literally rather than in quotes. Terraform 0.11 and earlier required quotes, but quoted references are now deprecated and will be removed in a future version of Terraform. Remove the quotes surrounding this reference to silence this warning. | 5    |

  Scenario: Quoted reference in resource `provider` attribute
    Given a configuration file containing:
      """
      provider "null" {
        alias = "foo"
      }

      resource "null_resource" "test" {
        provider = "null.foo" # Quoted reference
      }
      """
    When the configuration is parsed
    Then the resource "null_resource" "test" should be correctly assigned to provider "null.foo"
    And a warning diagnostic should be reported with:
      | Summary                        | Detail Contain                                                                                                                                                                      | Line |
      | Quoted references are deprecated | In this context, references are expected literally rather than in quotes. Terraform 0.11 and earlier required quotes, but quoted references are now deprecated and will be removed in a future version of Terraform. Remove the quotes surrounding this reference to silence this warning. | 6    |

  Scenario: Quoted keywords in provisioner `when` and `on_failure` attributes
    Given a configuration file containing:
      """
      resource "null_resource" "a" {
        provisioner "local-exec" {
          command    = "echo hello"
          when       = "create" # Quoted keyword
          on_failure = "fail"   # Quoted keyword
        }
      }
      """
    When the configuration is parsed
    Then the "local-exec" provisioner for "null_resource" "a" should have its `when` attribute correctly set to "create"
    And its `on_failure` attribute correctly set to "fail"
    And a warning diagnostic should be reported for the `when` attribute with:
      | Summary                     | Detail Contain                                                                                                                                                                   | Line |
      | Quoted keywords are deprecated | In this context, keywords are expected literally rather than in quotes. Terraform 0.11 and earlier required quotes, but quoted keywords are now deprecated and will be removed in a future version of Terraform. Remove the quotes surrounding this keyword to silence this warning. | 4    |
    And a warning diagnostic should be reported for the `on_failure` attribute with:
      | Summary                     | Detail Contain                                                                                                                                                                   | Line |
      | Quoted keywords are deprecated | In this context, keywords are expected literally rather than in quotes. Terraform 0.11 and earlier required quotes, but quoted keywords are now deprecated and will be removed in a future version of Terraform. Remove the quotes surrounding this keyword to silence this warning. | 5    |

  Scenario: Quoted event keyword in `action_trigger` events list
    Given a configuration file containing:
      """
      action "email" "notify" {}

      resource "null_resource" "example" {
        lifecycle {
          action_trigger {
            events  = ["before_create"] # Quoted keyword
            actions = [action.email.notify]
          }
        }
      }
      """
    When the configuration is parsed
    Then the `action_trigger` for "null_resource" "example" should correctly register the "before_create" event
    And a warning diagnostic should be reported for the "before_create" event with:
      | Summary                     | Detail Contain                                                                                                                                                                   |
      | Quoted keywords are deprecated | In this context, keywords are expected literally rather than in quotes. Terraform 0.11 and earlier required quotes, but quoted keywords are now deprecated and will be removed in a future version of Terraform. Remove the quotes surrounding this keyword to silence this warning. |

  Scenario: Legacy `ignore_changes = ["*"]` syntax
    Given a configuration file containing:
      """
      resource "null_resource" "legacy_ignore" {
        lifecycle {
          ignore_changes = ["*"] # Legacy star syntax
        }
      }
      """
    When the configuration is parsed
    Then the resource "null_resource" "legacy_ignore" should have its `ignore_changes` behavior set equivalent to `all`
    And a warning diagnostic should be reported for the `ignore_changes` attribute with:
      | Summary                                                      | Detail Contain                                                                                                                               |
      | Deprecated usage of `ignore_changes = ["*"]`                 | The special list element \"*\" is deprecated. To ignore all attributes, use `ignore_changes = all` instead. This warning may become an error in a future version. |
      # Note: The exact wording and location of this warning depends on the lifecycle block decoder,
      # as shimIsIgnoreChangesStar itself doesn't emit it.
```
