# Auto-generated by Jules forterraform-enterprise-data team
# Based on logic in internal/configs/config.go (EffectiveRequiredProviderConfigs)

Feature: Determining Effective Required Provider Configurations for a Module

  This feature describes how Terraform determines the set of provider
  configurations that a module effectively requires its caller to pass in.
  This considers the module's own `provider` blocks, its `required_providers`
  settings, providers implicitly needed by its resources/data sources/imports,
  and providers needed by child modules it calls (especially when not using
  an explicit `providers` argument in the module call).

  Background:
    Given a parent module configuration
    And a child module "child" configuration

  Scenario: Child module with no explicit provider needs and no resources
    Given the child module "child" has no `required_providers` and no resources
    When the parent module calls "child" without an explicit `providers` block
    Then the "child" module should have zero effective required provider configurations

  Scenario: Child module with an implicit default provider need from a resource
    Given the child module "child" contains:
      """
      resource "aws_instance" "foo" {}
      """
    And the child module "child" has no `required_providers` for "aws"
    When the parent module calls "child" without an explicit `providers` block
    Then the "child" module should effectively require the parent to provide:
      | Provider FQN          | Alias | Explicitly Requested by Child |
      | default.host/-/aws    |       | false                         |

  Scenario: Child module with an explicit `required_providers` entry (default provider)
    Given the child module "child" contains:
      """
      terraform {
        required_providers {
          myaws = { # local name in child
            source  = "hashicorp/aws"
            version = "~> 4.0"
          }
        }
      }
      resource "myaws_instance" "bar" {} # Uses local name myaws
      """
    When the parent module calls "child" without an explicit `providers` block
    Then the "child" module should effectively require the parent to provide:
      | Provider FQN                 | Alias | Explicitly Requested by Child | Child's Local Name |
      | default.host/hashicorp/aws |       | true                          | myaws              |
      # The parent is asked for default hashicorp/aws, child maps it to its local name 'myaws'

  Scenario: Child module with an explicit `required_providers` entry and an alias
    Given the child module "child" contains:
      """
      terraform {
        required_providers {
          myaws = {
            source  = "hashicorp/aws"
            version = "~> 4.0"
            configuration_aliases = [ aws.alternate ] # child expects parent to pass aws.alternate
          }
        }
      }
      resource "myaws_instance" "baz" {
        provider = myaws.alternate # Uses aliased provider from child's perspective
      }
      """
    When the parent module calls "child" without an explicit `providers` block
    Then the "child" module should effectively require the parent to provide:
      | Provider FQN                 | Alias     | Explicitly Requested by Child | Child's Local Name Configuration Alias |
      | default.host/hashicorp/aws | alternate | true                          | aws.alternate (mapped from myaws.alternate) |

  Scenario: Child module defines its own `provider` block (not a required config)
    Given the child module "child" contains:
      """
      provider "aws" {
        region = "us-west-1" # Child configures its own default 'aws'
      }
      resource "aws_instance" "foo" {} # Implicitly uses child's 'aws'
      """
    When the parent module calls "child" without an explicit `providers` block
    Then the "child" module should have zero effective required provider configurations for "aws" from the parent
    # Because the child provides its own 'aws' configuration.

  Scenario: Child module calls another grandchild module (implicit provider passing)
    Given the child module "child" calls a grandchild module "grandchild" without an explicit `providers` block:
      """
      module "grandchild" {
        source = "./grandchild"
      }
      """
    And the grandchild module "grandchild" contains:
      """
      resource "google_project" "project" {} # Needs 'google' provider
      """
    When the parent module calls "child" without an explicit `providers` block
    Then the "child" module should effectively require the parent to provide:
      | Provider FQN             | Alias | Explicitly Requested by Child |
      | default.host/-/google    |       | false                         |
      # Because child needs to pass 'google' to grandchild

  Scenario: Child module calls grandchild with explicit `providers` block in child's call
    Given the child module "child" calls a grandchild module "grandchild" with an explicit `providers` block:
      """
      provider "gcp" { # Parent of grandchild (i.e., 'child' module) configures 'gcp'
        project = "my-child-project"
      }
      module "grandchild" {
        source    = "./grandchild"
        providers = {
          google = gcp # 'child' passes its 'gcp' as 'google' to 'grandchild'
        }
      }
      """
    And the grandchild module "grandchild" contains:
      """
      terraform {
        required_providers {
          google = { # grandchild expects 'google'
            source = "hashicorp/google"
          }
        }
      }
      resource "google_project" "project" {}
      """
    When the parent module calls "child" without an explicit `providers` block
    Then the "child" module should *not* list `default.host/hashicorp/google` as a directly required config from the parent *due to the grandchild's needs*
    But the "child" module itself will require its own `gcp` provider (which is `default.host/-/gcp`) to be configured by the parent.
    And the "child" module should effectively require the parent to provide:
      | Provider FQN             | Alias | Explicitly Requested by Child |
      | default.host/-/gcp       |       | false                         |


  Scenario: Child module has an import block for a resource needing a specific provider
    Given the child module "child" contains:
      """
      import {
        to = aws_instance.imported_one
        id = "i-12345"
      }
      # No explicit resource "aws_instance" "imported_one" block in child
      # No required_providers for "aws" in child
      """
    When the parent module calls "child" without an explicit `providers` block
    Then the "child" module should effectively require the parent to provide:
      | Provider FQN          | Alias | Explicitly Requested by Child |
      | default.host/-/aws    |       | false                         |

  Scenario: Child module has an import block with an explicit provider argument
    Given the child module "child" contains:
      """
      import {
        to = random_string.imported_two
        id = "someid"
        provider = random.special # Child's import specifies local name 'random.special'
      }
      terraform {
        required_providers {
          random = { # Child defines local name 'random'
             source = "hashicorp/random"
          }
        }
      }
      """
    When the parent module calls "child" without an explicit `providers` block
    Then the "child" module should effectively require the parent to provide:
      | Provider FQN                  | Alias   | Explicitly Requested by Child | Child's Local Name Configuration |
      | default.host/hashicorp/random | special | false                         | random.special                   |
```
