# Auto-generated by Jules forterraform-enterprise-data team
# Based on logic in internal/configs/config.go (CheckCoreVersionRequirements)
# and testdata/valid-files/required-version.tf

Feature: Processing `required_version` Constraints from Terraform Blocks

  This feature describes how Terraform's configuration loader processes
  `terraform { required_version = "..." }` blocks from modules in a
  configuration tree. It focuses on collecting these constraints and
  diagnosing syntax errors. The actual enforcement of these constraints
  against the running Terraform version is a separate process.

  Scenario: Single module with a valid `required_version`
    Given a root module configuration containing:
      """
      terraform {
        required_version = "~> 0.12.0"
      }
      """
    When the configuration's core version requirements are checked
    Then no diagnostics should be reported regarding the `required_version` syntax
    And the root module's `required_version` constraint should be "~> 0.12.0"

  Scenario: Root and child module both with valid `required_version` constraints
    Given a root module configuration that calls a child module "child"
    And the root module contains:
      """
      terraform {
        required_version = ">= 1.0.0"
      }
      module "child" {
        source = "./child"
      }
      """
    And the child module "child" contains:
      """
      terraform {
        required_version = ">= 1.1.0, < 2.0.0"
      }
      """
    When the configuration's core version requirements are checked
    Then no diagnostics should be reported regarding the `required_version` syntax from either module
    And the root module's `required_version` constraint should be ">= 1.0.0"
    And the child module "child"'s `required_version` constraint should be ">= 1.1.0, < 2.0.0"

  Scenario: Module with an invalid `required_version` constraint string
    Given a root module configuration containing:
      """
      terraform {
        required_version = "not-a-valid-version-constraint"
      }
      """
    When the configuration's core version requirements are checked
    Then a diagnostic error should be reported for the root module
    And its summary should be "Invalid required_version constraint"
    And its detail should contain "Invalid version constraint" or similar, indicating the syntax error.

  Scenario: Child module with an invalid `required_version` constraint string
    Given a root module configuration that calls a child module "child"
    And the root module contains:
      """
      module "child" {
        source = "./child"
      }
      """
    And the child module "child" contains:
      """
      terraform {
        required_version = ">= 1..0" # Invalid syntax
      }
      """
    When the configuration's core version requirements are checked
    Then a diagnostic error should be reported for the child module "child"
    And its summary should be "Invalid required_version constraint"
    And its detail should contain "Invalid version constraint" or similar, indicating the syntax error.

  Scenario: Module missing `required_version` attribute in terraform block
    Given a root module configuration containing:
      """
      terraform {
        # No required_version here
      }
      """
    When the configuration's core version requirements are checked
    Then no diagnostics should be reported (as `required_version` is optional)
    And the root module should have no `required_version` constraint defined.
```
