# Auto-generated by Jules forterraform-enterprise-data team
# Based on logic in internal/configs/config_build.go (specifically loadModule)

Feature: Root-Module-Only Block Restrictions During Configuration Build

  This feature describes how Terraform's configuration builder (`BuildConfig`)
  handles blocks that are only allowed or effective in the root module.
  Using such blocks in child modules should result in appropriate diagnostics.

  Scenario: Child module defines a `backend` block
    Given a root module configuration that calls a child module "child_with_backend"
    And the child module "child_with_backend" contains:
      """
      terraform {
        backend "local" {
          path = "child.tfstate"
        }
      }
      """
    When the configuration is built
    Then a warning diagnostic should be reported for the child module "child_with_backend"
    And its summary should be "Backend configuration ignored"
    And its detail should contain "Terraform expects backend configurations only in the root module"
    And the subject of the diagnostic should point to the child's `backend` block declaration.

  Scenario: Child module defines a `cloud` block
    Given a root module configuration that calls a child module "child_with_cloud"
    And the child module "child_with_cloud" contains:
      """
      terraform {
        cloud {
          organization = "my-org-in-child"
          workspaces {
            name = "child-ws"
          }
        }
      }
      """
    When the configuration is built
    Then a warning diagnostic should be reported for the child module "child_with_cloud"
    And its summary should be "Cloud configuration ignored"
    And its detail should contain "Terraform expects 'cloud' blocks to only be in the root module"
    And the subject of the diagnostic should point to the child's `cloud` block declaration.

  Scenario: Child module defines an `import` block
    Given a root module configuration that calls a child module "child_with_import"
    And the child module "child_with_import" contains:
      """
      import {
        to = aws_instance.example
        id = "i-12345"
      }
      resource "aws_instance" "example" {
        # Not actually configured, just for the import target
      }
      """
    When the configuration is built
    Then an error diagnostic should be reported for the child module "child_with_import"
    And its summary should be "Invalid import configuration"
    And its detail should contain "Import blocks are only allowed in the root module."
    And the subject of the diagnostic should point to the child's `import` block declaration.

  Scenario: Child module defines a `list` block (experimental query block)
    Given a root module configuration that calls a child module "child_with_list_block"
    And the child module "child_with_list_block" contains:
      """
      # Assuming 'list' block experiment is implicitly enabled for this test context if needed by parser
      list "aws_instance" "all_instances" {
        provider = aws
      }
      """
    When the configuration is built
    Then an error diagnostic should be reported for the child module "child_with_list_block"
    And its summary should be "Invalid list configuration"
    And its detail should contain "List blocks are only allowed in the root module."
    And the subject of the diagnostic should point to the child's `list` block declaration.

  Scenario: Root module defines `backend`, `cloud`, `import`, and `list` blocks (valid)
    Given a root module configuration containing:
      """
      terraform {
        backend "local" { path = "root.tfstate" }
        # cloud { organization = "root-org" } # Cannot have both backend and cloud
      }
      import {
        to = aws_instance.example
        id = "i-root123"
      }
      resource "aws_instance" "example" {}
      # list "aws_vpc" "all_vpcs" { provider = aws } # Assuming experiment enabled
      """
    When the configuration is built
    Then no diagnostics should be reported regarding these blocks being in the root module
    # Other validation errors (like backend vs cloud) might still occur but are not the focus here.
```
