# Auto-generated by Jules forterraform-enterprise-data team
# Based on logic in internal/configs/import.go and relevant test files.

Feature: Parsing `import` Blocks

  This feature describes how Terraform parses `import {}` blocks,
  validating their attributes and the structure of the target resource address.
  Import blocks are only allowed in the root module.

  Scenario Outline: Valid `import` block definitions
    Given a configuration file in the root module with an `import` block defined as:
      """
      <import_block_hcl>
      """
    And any necessary target resource (e.g., "aws_instance" "target") is declared
    When the configuration is parsed
    Then the import block should be successfully parsed
    And its `to` attribute should correctly reference "<expected_to_resource_type>" "<expected_to_resource_name>"
    And its `id` expression should be "<id_expression>" if "<id_expression>" is not empty
    And its `identity` expression should be "<identity_expression>" if "<identity_expression>" is not empty
    And its `for_each` expression should be "<for_each_expression>" if "<for_each_expression>" is not empty
    And its provider reference should be "<provider_ref>" if "<provider_ref>" is not empty
    And no critical parsing diagnostics should be reported for this import block

    Examples:
      | import_block_hcl                                                               | expected_to_resource_type | expected_to_resource_name | id_expression    | identity_expression | for_each_expression | provider_ref |
      | import { to = aws_instance.target, id = "i-12345" }                            | aws_instance              | target                    | "i-12345"        |                     |                     |              |
      | import { to = aws_instance.target, identity = flusso_resource_identity("foo") }  | aws_instance              | target                    |                  | flusso_resource_identity("foo") |                     |              |
      | import { to = aws_instance.target[0], id = "i-0" }                             | aws_instance              | target                    | "i-0"            |                     |                     |              |
      | import { to = aws_instance.target["mykey"], id = "i-key" }                      | aws_instance              | target                    | "i-key"          |                     |                     |              |
      | import { provider = myaws, to = aws_instance.target, id = "id1" }              | aws_instance              | target                    | "id1"            |                     |                     | myaws        |
      | import { for_each = var.imports, to = aws_instance.target[each.key], id = each.value } | aws_instance              | target                    | each.value       |                     | var.imports         |              |

  Scenario: Valid `import` block in JSON format with string expressions for `to` and `id`
    Given a JSON configuration file in the root module with an `import` block defined as:
      """
      {
        "import": {
          "to": "aws_instance.target",
          "id": "\"i-json123\""
        },
        "resource": {
          "aws_instance": {
            "target": {}
          }
        }
      }
      """
    When the configuration is parsed
    Then the import block should be successfully parsed
    And its `to` attribute should correctly reference "aws_instance" "target"
    And its `id` expression should be "\"i-json123\""
    And no critical parsing diagnostics should be reported for this import block

  Scenario Outline: Invalid `import` block definitions
    Given a configuration file in the root module with an `import` block defined as:
      """
      <import_block_hcl>
      """
    And any necessary related resources (e.g., "aws_instance" "target", module "child") are declared
    When the configuration is parsed
    Then a diagnostic error with summary "<expected_error_summary>" should be reported
    And if "<expected_error_detail_fragment>" is not empty, the error detail should contain "<expected_error_detail_fragment>"

    Examples:
      | import_block_hcl                                                                    | expected_error_summary      | expected_error_detail_fragment                     |
      | import { to = aws_instance.target }                                                 | Invalid import block        | At least one of 'id' or 'identity' must be specified. |
      | import { to = aws_instance.target, id = "i-1", identity = flusso_id("a") }         | Invalid import block        | Only one of 'id' or 'identity' can be specified.   |
      | import { id = "i-1" }                                                               | Missing required argument   | to                                                 | # Missing 'to'
      | import { to = data.aws_ami.ubuntu, id = "ami-123" }                                 | Invalid import address      | Only managed resources can be imported.            |
      | import { to = module.child.aws_instance.target, id = "i-m1", provider =aws.child } | Invalid import provider argument | The provider argument can only be specified      |

  Scenario: Import block `to` attribute referencing a resource with a `for_each`
    Given a configuration file in the root module with:
      """
      resource "aws_instance" "server" {
        for_each = toset(["one", "two"])
        ami = "ami-123"
      }
      import {
        to = aws_instance.server["one"]
        id = "i-server-one"
      }
      """
    When the configuration is parsed
    Then the import block targeting "aws_instance.server[\"one\"]" should be successfully parsed
    And its `to` attribute should correctly reference "aws_instance" "server"
    And no critical parsing diagnostics should be reported for this import block's `to` address resolution.
```
