# Auto-generated by Jules forterraform-enterprise-data team
# Based on logic in internal/configs/named_values.go (decodeLocalsBlock)
# and examples in internal/configs/testdata/valid-files/

Feature: Parsing `locals` Blocks

  This feature describes how Terraform parses `locals {}` blocks,
  validating the names of local values defined within them.

  Scenario: Valid `locals` block with multiple entries
    Given a configuration file with:
      """
      locals {
        foo    = "a string"
        bar    = 123
        is_set = true
        π      = 3.14159
      }
      """
    When the `locals` block is decoded
    Then a local value named "foo" should be defined with expression "a string"
    And a local value named "bar" should be defined with expression 123
    And a local value named "is_set" should be defined with expression true
    And a local value named "π" should be defined with expression 3.14159
    And no parsing diagnostics should be reported for these local values.

  Scenario: Empty `locals` block
    Given a configuration file with:
      """
      locals {
        # This block is intentionally empty
      }
      """
    When the `locals` block is decoded
    Then zero local values should be defined from this block
    And no parsing diagnostics should be reported.

  Scenario Outline: Invalid local value name
    Given a configuration file with a `locals` block defined as:
      """
      locals {
        <local_definition>
      }
      """
    When the `locals` block is decoded
    Then a diagnostic error with summary "Invalid local value name" should be reported
    And its detail should contain "must be a valid identifier"

    Examples:
      | local_definition       |
      | "123foo" = "val"       |
      | "foo-bar@!" = "val"    |
      | "" = "val"             | # Empty name

  Scenario: `locals` block in JSON format
    Given a JSON configuration file with:
      """
      {
        "locals": {
          "json_foo": "json string",
          "json_bar": false
        }
      }
      """
    When the `locals` block is decoded
    Then a local value named "json_foo" should be defined with expression "json string"
    And a local value named "json_bar" should be defined with expression false
    And no parsing diagnostics should be reported.
```
