# Auto-generated by Jules forterraform-enterprise-data team
# Covers tests in internal/configs/mock_provider_test.go

Feature: Mock Provider Data Merging

  This feature describes the behavior of merging MockData instances,
  which are used in testing Terraform configurations. It focuses on how
  mock resources, mock data sources, and overrides are combined, and
  how collisions are handled.

  Background:
    Given a "current" MockData instance
    And a "target" MockData instance

  Scenario Outline: Merging MockData with overwrite enabled (no collision diagnostics)
    When the "current" MockData is merged with the "target" MockData and overwrite is true
    Then the resulting MockData should have <expected_resources_count> mock resource(s)
    And the resulting MockData should have <expected_datasources_count> mock data source(s)
    And the resulting MockData should have <expected_overrides_count> override(s)
    And the mock resource "<resource1_type>" should have defaults "<resource1_defaults>"
    And the mock data source "<datasource1_type>" should have defaults "<datasource1_defaults>"
    And the override for target "<override1_target>" should have values "<override1_values>"
    And if "<resource2_type>" is not empty, the mock resource "<resource2_type>" should have defaults "<resource2_defaults>"
    And if "<datasource2_type>" is not empty, the mock data source "<datasource2_type>" should have defaults "<datasource2_defaults>"
    And if "<override2_target>" is not empty, the override for target "<override2_target>" should have values "<override2_values>"
    And no diagnostics should be reported

    Examples:
      | current_resources                                   | current_datasources                                     | current_overrides                                       | target_resources                                      | target_datasources                                        | target_overrides                                          | expected_resources_count | expected_datasources_count | expected_overrides_count | resource1_type  | resource1_defaults | datasource1_type   | datasource1_defaults | override1_target          | override1_values | resource2_type      | resource2_defaults | datasource2_type       | datasource2_defaults | override2_target              | override2_values |
      | {"test_resource": {"defaults": "current_res_val"}}  | {"test_data_source": {"defaults": "current_ds_val"}}    | {"test_resource.my_resource": {"values": "current_ov_val"}} | {}                                                    | {}                                                        | {}                                                        | 1                        | 1                          | 1                        | test_resource   | "current_res_val"  | test_data_source   | "current_ds_val"     | test_resource.my_resource | "current_ov_val" |                     |                    |                        |                      |                               |                  | # empty_target
      | {"test_resource": {"defaults": "current_res_val"}}  | {"test_data_source": {"defaults": "current_ds_val"}}    | {"test_resource.my_resource": {"values": "current_ov_val"}} | nil                                                   | nil                                                       | nil                                                       | 1                        | 1                          | 1                        | test_resource   | "current_res_val"  | test_data_source   | "current_ds_val"     | test_resource.my_resource | "current_ov_val" |                     |                    |                        |                      |                               |                  | # nil_target
      | {"test_resource": {"defaults": "current_res_val"}}  | {"test_data_source": {"defaults": "current_ds_val"}}    | {"test_resource.my_resource": {"values": "current_ov_val"}} | {"test_resource": {"defaults": "target_res_val"}}     | {"test_data_source": {"defaults": "target_ds_val"}}       | {"test_resource.my_resource": {"values": "target_ov_val"}} | 1                        | 1                          | 1                        | test_resource   | "current_res_val"  | test_data_source   | "current_ds_val"     | test_resource.my_resource | "current_ov_val" |                     |                    |                        |                      |                               |                  | # all_collisions (current wins)
      | {"test_resource": {"defaults": "current_res_val"}}  | {"test_data_source": {"defaults": "current_ds_val"}}    | {"test_resource.my_resource": {"values": "current_ov_val"}} | {"test_resource_two": {"defaults": "target_res_val"}} | {"test_data_source_two": {"defaults": "target_ds_val"}}  | {"test_resource.my_other_resource": {"values": "target_ov_val"}} | 2                        | 2                          | 2                        | test_resource   | "current_res_val"  | test_data_source   | "current_ds_val"     | test_resource.my_resource | "current_ov_val" | test_resource_two | "target_res_val"   | test_data_source_two | "target_ds_val"      | test_resource.my_other_resource | "target_ov_val"  | # no_collisions

  Scenario Outline: Merging MockData with overwrite disabled (collision diagnostics reported)
    When the "current" MockData is merged with the "target" MockData and overwrite is false
    Then the resulting MockData should have <expected_resources_count> mock resource(s)
    And the resulting MockData should have <expected_datasources_count> mock data source(s)
    And the resulting MockData should have <expected_overrides_count> override(s)
    And the mock resource "<resource1_type>" should have defaults "<resource1_defaults>"
    And the mock data source "<datasource1_type>" should have defaults "<datasource1_defaults>"
    And the override for target "<override1_target>" should have values "<override1_values>"
    And if "<resource2_type>" is not empty, the mock resource "<resource2_type>" should have defaults "<resource2_defaults>"
    And if "<datasource2_type>" is not empty, the mock data source "<datasource2_type>" should have defaults "<datasource2_defaults>"
    And if "<override2_target>" is not empty, the override for target "<override2_target>" should have values "<override2_values>"
    And if "<expected_diags>" is not empty, then diagnostics matching "<expected_diags>" should be reported

    Examples:
      | current_resources                                   | current_datasources                                     | current_overrides                                       | target_resources                                      | target_datasources                                        | target_overrides                                          | expected_resources_count | expected_datasources_count | expected_overrides_count | resource1_type  | resource1_defaults | datasource1_type   | datasource1_defaults | override1_target          | override1_values | resource2_type      | resource2_defaults | datasource2_type       | datasource2_defaults | override2_target              | override2_values | expected_diags |
      | {"test_resource": {"defaults": "current_res_val"}}  | {"test_data_source": {"defaults": "current_ds_val"}}    | {"test_resource.my_resource": {"values": "current_ov_val"}} | {}                                                    | {}                                                        | {}                                                        | 1                        | 1                          | 1                        | test_resource   | "current_res_val"  | test_data_source   | "current_ds_val"     | test_resource.my_resource | "current_ov_val" |                     |                    |                        |                      |                               |                  |                | # empty_target
      | {"test_resource": {"defaults": "current_res_val"}}  | {"test_data_source": {"defaults": "current_ds_val"}}    | {"test_resource.my_resource": {"values": "current_ov_val"}} | nil                                                   | nil                                                       | nil                                                       | 1                        | 1                          | 1                        | test_resource   | "current_res_val"  | test_data_source   | "current_ds_val"     | test_resource.my_resource | "current_ov_val" |                     |                    |                        |                      |                               |                  |                | # nil_target
      | {"test_resource": {"defaults": "current_res_val"}}  | {"test_data_source": {"defaults": "current_ds_val"}}    | {"test_resource.my_resource": {"values": "current_ov_val"}} | {"test_resource": {"defaults": "target_res_val"}}     | {"test_data_source": {"defaults": "target_ds_val"}}       | {"test_resource.my_resource": {"values": "target_ov_val"}} | 1                        | 1                          | 1                        | test_resource   | "current_res_val"  | test_data_source   | "current_ds_val"     | test_resource.my_resource | "current_ov_val" |                     |                    |                        |                      |                               |                  | A mock_resource "test_resource" block already exists;A mock_data "test_data_source" block already exists;An override block for test_resource.my_resource already exists | # all_collisions (current wins, diags reported)
      | {"test_resource": {"defaults": "current_res_val"}}  | {"test_data_source": {"defaults": "current_ds_val"}}    | {"test_resource.my_resource": {"values": "current_ov_val"}} | {"test_resource_two": {"defaults": "target_res_val"}} | {"test_data_source_two": {"defaults": "target_ds_val"}}  | {"test_resource.my_other_resource": {"values": "target_ov_val"}} | 2                        | 2                          | 2                        | test_resource   | "current_res_val"  | test_data_source   | "current_ds_val"     | test_resource.my_resource | "current_ov_val" | test_resource_two | "target_res_val"   | test_data_source_two | "target_ds_val"      | test_resource.my_other_resource | "target_ov_val"  |                | # no_collisions
```
