# Auto-generated by Jules forterraform-enterprise-data team
# Based on logic in internal/configs/module_merge.go

Feature: Specific Attribute Merge Behaviors and Restrictions in Overrides

  This feature describes specific behaviors when attributes of configuration
  blocks are merged from override files, including restrictions on certain
  attributes like `depends_on` and validation logic applied after merging
  variable attributes.

  Scenario Outline: Attempting to override `depends_on` is not allowed
    Given a primary file "main.tf" with a "<block_type>" named "<block_name>" defined as:
      """
      <base_block_hcl_with_depends_on>
      """
    And an override file "override.tf" with the "<block_type>" named "<block_name>" defined as:
      """
      <override_block_hcl_with_depends_on>
      """
    When the module is constructed
    Then a diagnostic error with summary "Unsupported override" should be reported
    And its detail should state "The depends_on argument may not be overridden."
    And the subject of the error should point to the `depends_on` in the override.

    Examples:
      | block_type | block_name | base_block_hcl_with_depends_on                               | override_block_hcl_with_depends_on                           |
      | output     | my_output  | output "my_output" { value = "val", depends_on = [res.a] }    | output "my_output" { depends_on = [res.b] }                 |
      | module     | my_module  | module "my_module" { source = "./a", depends_on = [res.a] }  | module "my_module" { depends_on = [res.b] }                |
      | resource   | my_res     | resource "null_resource" "my_res" { depends_on = [res.a] }   | resource "null_resource" "my_res" { depends_on = [res.b] } |
      | action     | my_action  | action "custom" "my_action" { depends_on = [res.a] }         | action "custom" "my_action" { depends_on = [res.b] }       |
      # Define dummy res.a and res.b for syntax validity if needed by parser for these tests.

  Scenario: Variable type override makes existing default value invalid
    Given a primary file "main.tf" with:
      """
      variable "test_var" {
        type    = string
        default = "not-a-number"
      }
      """
    And an override file "override.tf" with:
      """
      variable "test_var" {
        type = number # Override type to number
      }
      """
    When the module is constructed
    Then a diagnostic error with summary "Invalid default value for variable" should be reported for "test_var"
    And its detail should contain "Overriding this variable's type constraint has made its default value invalid" (or similar indicating type/default mismatch).

  Scenario: Variable default override is incompatible with existing type
    Given a primary file "main.tf" with:
      """
      variable "test_var" {
        type    = number
        default = 123
      }
      """
    And an override file "override.tf" with:
      """
      variable "test_var" {
        default = "not-a-number" # Override default to a string
      }
      """
    When the module is constructed
    Then a diagnostic error with summary "Invalid default value for variable" should be reported for "test_var"
    And its detail should contain "The overridden default value for this variable is not compatible with the variable's type constraint" (or similar).

  Scenario: Variable default override to null when variable is not nullable
    Given a primary file "main.tf" with:
      """
      variable "test_var" {
        type        = string
        default     = "initial"
        nullable    = false
      }
      """
    And an override file "override.tf" with:
      """
      variable "test_var" {
        default = null # Override default to null
      }
      """
    When the module is constructed
    Then a diagnostic error with summary "Invalid default value for variable" should be reported for "test_var"
    And its detail should be "A null default value is not valid when nullable=false."

  Scenario: Variable type and default overridden, new combination is valid
    Given a primary file "main.tf" with:
      """
      variable "test_var" {
        type    = string
        default = "abc"
      }
      """
    And an override file "override.tf" with:
      """
      variable "test_var" {
        type    = number
        default = 456
      }
      """
    When the module is constructed
    Then variable "test_var" should have type "number" and default value 456
    And no "Invalid default value" error should be reported for "test_var".

  Scenario: Local value is entirely replaced by override
    Given a primary file "main.tf" with:
      """
      locals {
        my_local = "base value"
      }
      """
    And an override file "override.tf" with:
      """
      locals {
        my_local = "override value" # This expression completely replaces the base
      }
      """
    When the module is constructed
    Then the local value "my_local" should be "override value"
    And its declaration range should point to the override file.
```
