# Auto-generated by Jules forterraform-enterprise-data team
# Covers tests in internal/configs/module_call_test.go

Feature: Module Call Parsing and Interpretation

  This feature describes how Terraform parses module call blocks from configuration
  files and how it interprets different module source address types.

  Scenario: Parsing various module call definitions
    Given a configuration file "module-calls.tf" with the following content:
      """
      module "foo" {
        source = "./foo"
      }

      module "bar" {
        source = "hashicorp/bar/aws"
      }

      module "baz" {
        source   = "git::https://example.com/"
        for_each = { "a" = 1 }
        count    = 2 # Invalid combination
        depends_on = [
          module.bar
        ]
        providers = {
          aws = aws.foo
        }
      }
      """
    When the configuration file "module-calls.tf" is loaded
    Then the following diagnostic should be reported:
      | Severity | Summary                                       | Detail                                                                                                                                     | File            | Line | Column |
      | Error    | Invalid combination of "count" and "for_each" | The "count" and "for_each" meta-arguments are mutually-exclusive, only one should be used to be explicit about the number of resources to be created. | module-calls.tf | 20   | 3      |
    And the loaded file should contain 3 module calls
    And the first module call should have:
      | Name          | SourceAddrRaw | SourceAddrType      | SourceSet | DeclRangeStartLine | DeclRangeStartCol | SourceAddrRangeStartLine | SourceAddrRangeStartCol |
      | foo           | ./foo         | Local               | true      | 2                  | 1                 | 3                        | 12                      |
    And the second module call should have:
      | Name          | SourceAddrRaw       | SourceAddrType      | SourceAddrHost              | SourceAddrNamespace | SourceAddrName | SourceAddrTargetSystem | SourceSet | DeclRangeStartLine | DeclRangeStartCol | SourceAddrRangeStartLine | SourceAddrRangeStartCol |
      | bar           | hashicorp/bar/aws   | Registry            | default.host                | hashicorp           | bar            | aws                    | true      | 7                  | 1                 | 8                        | 12                      |
    And the third module call should have:
      | Name          | SourceAddrRaw             | SourceAddrType      | SourceAddrPackage           | SourceSet | DeclRangeStartLine | DeclRangeStartCol | SourceAddrRangeStartLine | SourceAddrRangeStartCol |
      | baz           | git::https://example.com/ | Remote              | git::https://example.com/   | true      | 14                 | 1                 | 15                       | 12                      |
    And the third module call should have 1 depends_on entry:
      | Type   | Name   | AttrName |
      | module | bar    |          |
    And the third module call should have 1 passed provider config:
      | InChildName | InParentName | InParentAlias |
      | aws         | aws          | foo           |
    # Note: config, count, and for_each bodies are not deeply inspected in this test's BDD representation for brevity,
    # as the original Go test explicitly nils them out for focus. The "count" and "for_each" conflict is tested by diagnostics.

  Scenario Outline: Determining if a module source address enters a new package
    Given a module source address "<source_addr>"
    When it is determined if the source address enters a new package
    Then the result should be <enters_new_package>

    Examples:
      | source_addr                              | enters_new_package |
      | ./                                       | false              |
      | ../bork                                  | false              |
      | /absolute/path                           | true               |
      | github.com/example/foo                   | true               |
      | hashicorp/subnets/cidr                   | true               |
      | registry.terraform.io/hashicorp/subnets/cidr | true               |
      | git::https://example.com/foo.git         | true               |
      | hg::http://example.com/foo               | true               |
      | s3::https://s3.amazonaws.com/bucket/key  | true               |
      | gcs::https://www.googleapis.com/storage/v1/b/bucket/o/key | true |
```
