# Auto-generated by Jules forterraform-enterprise-data team
# Covers tests in internal/configs/module_test.go

Feature: Module Configuration Parsing and Provider Handling

  This feature describes how Terraform modules are parsed, focusing on
  provider configurations (explicit, implied, FQNs, local names),
  required_providers blocks (including overrides and load order),
  and backend/cloud/state_store configurations (including overrides and conflicts).

  Background:
    Given a Terraform module is loaded from a directory

  Scenario: Provider FQNs and Local Names
    Given a module is loaded from "testdata/providers-explicit-fqn"
    Then the module should have a provider local name "foo-test" for FQN "default.host/foo/test"
    And looking up local name for FQN "default.host/foo/test" should return "foo-test"
    And looking up local name for FQN "default.host/nonexist/nonexist" should return "nonexist"
    And the module should have a provider local name "terraform" for FQN "default.host/not-builtin/not-terraform"
    And the provider FQN for local provider config "foo-test" should be "default.host/foo/test"

  Scenario: Resource Provider Assignment with FQNs in Nested Modules
    Given a nested module configuration is loaded from "testdata/valid-modules/nested-providers-fqns"
    Then in the root module:
      | Resource Name             | Expected Provider FQN       |
      | test_instance.explicit    | default.host/foo/test       |
      | test_instance.implicit    | default.host/-/test         |
      | data.test_resource.explicit | default.host/foo/test       |
    And in the child module "child":
      | Resource Name             | Expected Provider FQN       |
      | test_instance.explicit    | default.host/bar/test       |
      | test_instance.implicit    | default.host/-/test         |

  Scenario: Multiple required_providers blocks
    Given a module is loaded from "testdata/invalid-modules/multiple-required-providers"
    Then a diagnostic error containing "Duplicate required providers configuration" should be reported

  Scenario: required_providers loaded after resource definitions
    Given a module is loaded from "testdata/valid-modules/required-providers-after-resource"
    Then the provider requirement for local name "test" should be for FQN "default.host/foo/test"
    And the managed resource "test_instance.my-instance" should be assigned provider FQN "default.host/foo/test"

  Scenario: required_providers overrides
    Given a module is loaded from "testdata/valid-modules/required-providers-overrides"
    Then the provider requirement for local name "foo" should be for FQN "default.host/acme/foo"
    And the managed resource "foo_thing.ft" should be assigned provider FQN "default.host/acme/foo"
    And the provider requirement for local name "bar" should be for FQN "default.host/blorp/bar" with version "~>2.0.0"
    And the managed resource "bar_thing.bt" should be assigned provider FQN "default.host/blorp/bar"

  Scenario: Implied provider assignment based on resource type
    Given a module is loaded from "testdata/valid-modules/implied-providers"
    Then the provider requirement for local name "foo" should be for FQN "registry.acme.corp/acme/foo"
    And the provider requirement for local name "whatever" should be for FQN "default.host/acme/something"
    And the following resources should be assigned the specified provider FQNs:
      | Resource Address        | Expected Provider FQN                |
      | foo_resource.a          | registry.acme.corp/acme/foo        |
      | data.foo_resource.b     | registry.acme.corp/acme/foo        |
      | bar_resource.c          | default.host/-/bar                 |
      | data.bar_resource.d     | default.host/-/bar                 |
      | whatever_resource.e     | default.host/acme/something        |
      | data.whatever_resource.f| default.host/acme/something        |

  Scenario: Implied provider lookup for unqualified type
    Given a module is loaded from "testdata/valid-modules/implied-providers"
    Then the implied provider for unqualified type "foo" should be "registry.acme.corp/acme/foo"
    And the implied provider for unqualified type "whatever" should be "default.host/acme/something"
    And the implied provider for unqualified type "bar" should be "default.host/-/bar"
    And the implied provider for unqualified type "terraform" should be "built_in/-/terraform"

  Scenario: Backend configuration overrides
    When a module is loaded from "testdata/valid-modules/override-backend"
    Then the module backend type should be "bar"
    And the module backend config attribute "path" should be "CHANGED/relative/path/to/terraform.tfstate"

  Scenario: Backend configuration override with no base backend
    When a module is loaded from "testdata/valid-modules/override-backend-no-base"
    Then the module backend configuration should not be nil

  Scenario: Cloud configuration overrides backend configuration
    When a module is loaded from "testdata/valid-modules/override-backend-with-cloud"
    Then the module backend configuration should be nil
    And the module cloud configuration should not be nil

  Scenario: Cloud configuration overrides cloud configuration
    When a module is loaded from "testdata/valid-modules/override-cloud"
    Then the module cloud config attribute "organization" should be "CHANGED"
    And the module cloud config attribute "should_not_be_present_with_override" should be nil

  Scenario: Cloud configuration override with no base cloud/backend
    When a module is loaded from "testdata/valid-modules/override-cloud-no-base"
    Then the module cloud configuration should not be nil

  Scenario: Backend configuration overrides cloud configuration
    When a module is loaded from "testdata/valid-modules/override-cloud-with-backend"
    Then the module cloud configuration should be nil
    And the module backend type should be "override"
    And the module backend config attribute "path" should be "value from override"

  Scenario: Duplicate cloud blocks in override file
    Given a module is loaded from "testdata/invalid-modules/override-cloud-duplicates"
    Then a diagnostic error containing "Duplicate HCP Terraform configurations" should be reported

  Scenario: Multiple backend blocks in module
    Given a module is loaded from "testdata/invalid-modules/multiple-backends"
    Then a diagnostic error containing "Duplicate 'backend' configuration block" should be reported

  Scenario: Multiple cloud blocks in module
    Given a module is loaded from "testdata/invalid-modules/multiple-cloud"
    Then a diagnostic error containing "Duplicate HCP Terraform configurations" should be reported

  Scenario Outline: Conflicting backend, cloud, and state_store configurations
    Given a module is loaded from "<module_dir>" with experiments <allow_experiments>
    Then a diagnostic error containing "<expected_message>" should be reported

    Examples:
      | module_dir                                                        | expected_message                                                                 | allow_experiments |
      | testdata/invalid-modules/conflict-cloud-backend                   | Conflicting 'cloud' and 'backend' configuration blocks are present               | false             |
      | testdata/invalid-modules/conflict-cloud-backend-separate-files    | Conflicting 'cloud' and 'backend' configuration blocks are present               | false             |
      | testdata/invalid-modules/conflict-cloud-statestore                | Conflicting 'cloud' and 'state_store' configuration blocks are present           | true              |
      | testdata/invalid-modules/conflict-cloud-statestore-separate-files | Conflicting 'cloud' and 'state_store' configuration blocks are present           | true              |
      | testdata/invalid-modules/conflict-statestore-backend              | Conflicting 'state_store' and 'backend' configuration blocks are present         | true              |
      | testdata/invalid-modules/conflict-statestore-backend-separate-files | Conflicting 'state_store' and 'backend' configuration blocks are present         | true              |
      | testdata/invalid-modules/conflict-cloud-backend-statestore        | Only one of 'cloud', 'state_store', or 'backend' configuration blocks are allowed | true              |

  Scenario: State_store configuration overrides state_store configuration
    When a module is loaded from "testdata/valid-modules/override-state-store"
    Then the module state_store configuration should not be nil
    And the module state_store type should be "foo_override"
    And the module state_store config attribute "custom_attr" should be "override"
    And the module state_store provider local name should be "bar"

  Scenario: State_store configuration override with no base
    When a module is loaded from "testdata/valid-modules/override-state-store-no-base"
    Then the module state_store configuration should not be nil

  Scenario: State_store configuration overrides backend configuration
    When a module is loaded from "testdata/valid-modules/override-backend-with-state-store"
    Then the module backend configuration should be nil
    And the module state_store configuration should not be nil
    And the module state_store type should be "foo_override"

  Scenario: State_store configuration overrides cloud configuration
    When a module is loaded from "testdata/valid-modules/override-cloud-with-state-store"
    Then the module cloud configuration should be nil
    And the module state_store configuration should not be nil
    And the module state_store type should be "foo_override"

  Scenario: Multiple state_store blocks in module
    Given a module is loaded from "testdata/invalid-modules/multiple-state-store"
    Then a diagnostic error containing "Duplicate 'state_store' configuration block" should be reported
```
