# Auto-generated by Jules forterraform-enterprise-data team
# Based on logic in internal/configs/module_merge_body.go (MergeBodies)

Feature: Merging HCL Bodies from Base and Override Files

  This feature describes how Terraform merges HCL bodies (attributes and
  nested blocks) when a configuration block (like a resource, provider,
  module call, or action) is defined in a primary file and then modified
  by an override file.

  Background:
    Given a primary configuration file "main.tf"
    And an override file "override.tf"

  Scenario: Attribute merging - Override attributes take precedence
    Given "main.tf" contains a resource definition:
      """
      resource "test_resource" "example" {
        attr1 = "base value 1"
        attr2 = "base value 2"
        nested_block {
          block_attr = "base block value"
        }
      }
      """
    And "override.tf" contains a corresponding resource definition:
      """
      resource "test_resource" "example" {
        attr2 = "override value 2" # Overrides base attr2
        attr3 = "override value 3" # New attribute
      }
      """
    When the module is constructed
    Then the merged "test_resource" "example" should have attribute "attr1" with value "base value 1"
    And it should have attribute "attr2" with value "override value 2"
    And it should have attribute "attr3" with value "override value 3"
    And it should still contain one "nested_block" (as it wasn't overridden by type)

  Scenario: Nested block merging - Override blocks of a type replace all base blocks of that type
    Given "main.tf" contains a resource definition:
      """
      resource "aws_security_group" "example" {
        name = "main-sg"
        description = "Main SG"

        ingress { # Base ingress block 1
          from_port   = 80
          to_port     = 80
          protocol    = "tcp"
          cidr_blocks = ["0.0.0.0/0"]
        }
        ingress { # Base ingress block 2
          from_port   = 443
          to_port     = 443
          protocol    = "tcp"
          cidr_blocks = ["0.0.0.0/0"]
        }
        egress { # Base egress block
          from_port   = 0
          to_port     = 0
          protocol    = "-1"
          cidr_blocks = ["0.0.0.0/0"]
        }
      }
      """
    And "override.tf" contains a corresponding resource definition:
      """
      resource "aws_security_group" "example" {
        description = "Overridden SG description" # Attribute override

        ingress { # Override ingress block 1
          from_port   = 22
          to_port     = 22
          protocol    = "tcp"
          cidr_blocks = ["10.0.0.0/8"]
        }
        # No egress block in override
      }
      """
    When the module is constructed
    Then the merged "aws_security_group" "example" should have attribute "name" with value "main-sg"
    And it should have attribute "description" with value "Overridden SG description"
    And it should contain exactly 1 "ingress" block
    And that "ingress" block should have "from_port" = 22 and "cidr_blocks" = ["10.0.0.0/8"]
    And it should contain exactly 1 "egress" block (from base, as `egress` type wasn't in override)
    And that "egress" block should have "protocol" = "-1"

  Scenario: Nested block merging - Override with no blocks of a type preserves base blocks of that type
    Given "main.tf" contains a resource definition:
      """
      resource "test_resource" "example" {
        attr = "base"
        setting {
          name = "base_setting_1"
        }
        setting {
          name = "base_setting_2"
        }
      }
      """
    And "override.tf" contains a corresponding resource definition:
      """
      resource "test_resource" "example" {
        attr = "override" # Only overrides an attribute
        # No 'setting' blocks in this override
      }
      """
    When the module is constructed
    Then the merged "test_resource" "example" should have attribute "attr" with value "override"
    And it should contain 2 "setting" blocks
    And one "setting" block should have "name" = "base_setting_1"
    And the other "setting" block should have "name" = "base_setting_2"

  Scenario: Nested block merging - `dynamic` block in override replaces static and dynamic blocks of same type from base
    Given "main.tf" contains a resource definition:
      """
      resource "test_resource" "example" {
        dynamic "label" { # Base dynamic block for "label"
          for_each = { "a" = "b" }
          content {
            name  = label.key
            value = label.value
          }
        }
        label { # Base static block for "label"
            name = "static_base_label"
            value = "static_base_value"
        }
        other_block {} # Unrelated block
      }
      """
    And "override.tf" contains a corresponding resource definition:
      """
      resource "test_resource" "example" {
        dynamic "label" { # Override dynamic block for "label"
          for_each = { "x" = "y" }
          content {
            name  = "override_${label.key}"
            value = label.value
          }
        }
      }
      """
    When the module is constructed
    Then the merged "test_resource" "example" should contain exactly 1 "dynamic" block with label "label"
    And its `for_each` expression should be '{ "x" = "y" }'
    And it should contain no static "label" blocks
    And it should still contain one "other_block"

  Scenario: Nested block merging - Static block in override replaces dynamic and static blocks of same type from base
    Given "main.tf" contains a resource definition:
      """
      resource "test_resource" "example" {
        dynamic "label" { # Base dynamic block for "label"
          for_each = { "a" = "b" }
          content {
            name  = label.key
            value = label.value
          }
        }
      }
      """
    And "override.tf" contains a corresponding resource definition:
      """
      resource "test_resource" "example" {
        label { # Override static block for "label"
            name = "override_static_label"
            value = "override_static_value"
        }
      }
      """
    When the module is constructed
    Then the merged "test_resource" "example" should contain exactly 1 static "label" block
    And that "label" block should have "name" = "override_static_label"
    And it should contain no "dynamic" blocks with label "label"
```
