# Auto-generated by Jules forterraform-enterprise-data team
# Based on logic in internal/configs/module.go (NewModule, appendFile, mergeFile)

Feature: Module File Processing - Appending, Merging, and Override Rules

  This feature describes how Terraform's `NewModule` function processes primary
  configuration files (.tf) and override files (_override.tf) to construct
  a single module definition. It covers detection of duplicate blocks in
  primary files and the specific rules for how override files modify or
  replace existing configurations.

  Background:
    Given a module directory being parsed

  Scenario Outline: Duplicate block definitions in primary configuration files
    Given a file "file_a.tf" with content:
      """
      <block_a_hcl>
      """
    And another file "file_b.tf" in the same directory with content:
      """
      <block_b_hcl>
      """
    When the module is constructed from these primary files
    Then a diagnostic error with summary "<expected_error_summary>" should be reported
    And its detail should contain "<expected_error_detail_fragment>"

    Examples:
      | block_a_hcl                                       | block_b_hcl                                       | expected_error_summary                 | expected_error_detail_fragment      |
      | variable "name" { type = string }                 | variable "name" { type = number }                 | Duplicate variable declaration         | A variable named "name"             |
      | resource "aws_instance" "web" { ami = "a" }       | resource "aws_instance" "web" { ami = "b" }       | Duplicate resource "aws_instance" configuration | A aws_instance resource named "web" |
      | provider "aws" { region = "us-east-1" }           | provider "aws" { region = "us-west-2" }           | Duplicate provider configuration       | A default (non-aliased) provider    |
      | provider "aws" { alias = "east"; region = "us-east-1" } | provider "aws" { alias = "east"; region = "us-west-1" } | Duplicate provider configuration       | A provider configuration for "aws" with alias "east" |
      | module "child" { source = "./a" }                 | module "child" { source = "./b" }                 | Duplicate module call                  | A module call named "child"         |
      | check "status" { assert { c=true, e="m"} }       | check "status" { assert { c=false, e="n"} }      | Duplicate check "status" configuration | A check block named "status"        |
      | action "http" "call" { url = "a.com" }            | action "http" "call" { url = "b.com" }            | Duplicate action "http" configuration  | An action named "call"              |
      | import { to = aws_instance.foo, id = "1" }        | import { to = aws_instance.foo, id = "2" }        | Duplicate import configuration for "aws_instance.foo" | An import block for the resource "aws_instance.foo" |
      # Note: Output duplication is in outputs_directory_parsing.feature
      # Note: required_providers duplication is in module_config.feature
      # Note: backend/cloud/state_store duplication/conflicts are in module_config.feature

  Scenario Outline: Valid override of attributes for existing blocks
    Given a primary file "main.tf" with content:
      """
      <base_block_hcl>
      """
    And an override file "override.tf" with content:
      """
      <override_block_hcl>
      """
    When the module is constructed
    Then the "<block_type>" named "<block_name>" should have its "<overridden_attribute>" set to "<expected_value>"
    And no "Missing base" or "Cannot override" errors should be reported for this override.

    Examples:
      | block_type | block_name | base_block_hcl                                  | override_block_hcl                                 | overridden_attribute | expected_value        |
      | variable   | test_var   | variable "test_var" { type = string }           | variable "test_var" { description = "Override" }   | description          | "Override"            |
      | local      | test_local | locals { test_local = "base" }                  | locals { test_local = "override" }                 | value (effective)    | "override"            | # Locals are fully replaced by name
      | output     | test_out   | output "test_out" { value = "base" }           | output "test_out" { description = "Override" }    | description          | "Override"            |
      | module     | test_mod   | module "test_mod" { source = "./base" }         | module "test_mod" { version = "1.1.0" }           | version              | "1.1.0"               |
      | resource   | test_res   | resource "null_resource" "test_res" {}          | resource "null_resource" "test_res" { triggers = {always_run = timestamp()} } | triggers (effective) | (map containing always_run) | # Resource bodies are merged
      | action     | test_act   | action "custom" "test_act" { base_config = 1 }  | action "custom" "test_act" { override_config = 2} | config (effective)   | (contains override_config) | # Action bodies are merged

  Scenario Outline: Invalid override attempt for non-existent or non-overridable blocks
    Given a primary file "main.tf" (it can be empty or contain unrelated blocks)
    And an override file "override.tf" with content:
      """
      <override_block_hcl>
      """
    When the module is constructed
    Then a diagnostic error with summary "<expected_error_summary>" should be reported.

    Examples:
      | override_block_hcl                               | expected_error_summary                               |
      | variable "non_existent_var" { type = string }    | Missing base variable declaration to override        |
      | locals { non_existent_local = "val" }            | Missing base local value definition to override      |
      | output "non_existent_out" { value = "val" }      | Missing base output definition to override           |
      | module "non_existent_mod" { source = "./mod" }   | Missing module call to override                      |
      | resource "null_resource" "non_existent_res" {}   | Missing resource to override                         |
      | provider "aws" { alias = "non_existent_alias" }  | Missing base provider configuration for override     | # For aliased provider
      | moved { from = a, to = b }                       | Cannot override 'moved' blocks                       |
      | import { to = aws_instance.foo, id = "id" }      | Cannot override 'import' blocks                      |
      | action "custom" "non_existent_act" {}            | Missing resource to override                         | # Error message says "Missing resource", should be "Missing action" ideally

  Scenario: Default (non-aliased) provider introduced by an override file
    Given an empty primary file "main.tf"
    And an override file "override.tf" with content:
      """
      provider "aws" {
        region = "us-east-1"
      }
      """
    When the module is constructed
    Then a provider "aws" (default alias) should exist with region "us-east-1"
    And no "Missing base provider configuration" error should be reported.

  Scenario: `core_version_constraints` overridden by an override file
    Given a primary file "main.tf" with content:
      """
      terraform {
        required_version = "~> 1.0"
      }
      """
    And an override file "override.tf" with content:
      """
      terraform {
        required_version = "~> 1.1"
      }
      """
    When the module is constructed
    Then the module's core version constraint should be "~> 1.1"
```
