# Auto-generated by Jules forterraform-enterprise-data team
# Based on logic in internal/configs/moved.go and internal/configs/moved_test.go
# and examples in internal/configs/testdata/valid-modules/moved-blocks/

Feature: Parsing `moved` Blocks for State Refactoring

  This feature describes how Terraform parses `moved {}` blocks, which are
  used to record the planned refactoring of resources or modules from one
  address to another, facilitating state migration.

  Scenario Outline: Valid `moved` block definitions
    Given a configuration file containing a `moved` block with:
      from = <from_address>
      to   = <to_address>
    When the configuration is parsed
    Then the `moved` block should be successfully parsed
    And its `from` endpoint should represent "<from_address_str>"
    And its `to` endpoint should represent "<to_address_str>"
    And no critical parsing diagnostics should be reported for this `moved` block

    Examples:
      | from_address          | to_address              | from_address_str      | to_address_str          |
      | test_instance.foo     | test_instance.bar       | test_instance.foo     | test_instance.bar       |
      | test_instance.foo     | test_instance.bar["bloop"] | test_instance.foo     | test_instance.bar["bloop"] |
      | module.a              | module.b                | module.a              | module.b                |
      | module.a              | module.a["foo"]         | module.a              | module.a["foo"]         |
      | test_instance.old     | module.new.test_instance.old | test_instance.old     | module.new.test_instance.old |
      | data.external.source  | data.external.dest      | data.external.source  | data.external.dest      |
      | aws_instance.a[0]     | aws_instance.b["one"]   | aws_instance.a[0]     | aws_instance.b["one"]   |

  Scenario Outline: Invalid `moved` block definitions due to attribute issues or type mismatch
    Given a configuration file containing a `moved` block defined as:
      """
      <moved_block_hcl>
      """
    When the configuration is parsed
    Then a diagnostic error with summary "<expected_error_summary>" should be reported
    And if "<expected_error_detail_fragment>" is not empty, its detail should contain "<expected_error_detail_fragment>"

    Examples:
      | moved_block_hcl                                 | expected_error_summary      | expected_error_detail_fragment |
      | moved { to = test_instance.bar }                | Missing required argument   | from                           | # Missing 'from'
      | moved { from = test_instance.foo }              | Missing required argument   | to                             | # Missing 'to'
      | moved { from = test_instance.foo, to = module.bar } | Invalid "moved" addresses | must either both refer to resources or both refer to modules |
      | moved { from = module.foo, to = test_instance.bar } | Invalid "moved" addresses | must either both refer to resources or both refer to modules |
      | moved { from = "invalid.syntax[", to = test_instance.bar } | Parsing HCL Traversal | (specific HCL error)           | # Invalid 'from' traversal
      | moved { from = test_instance.foo, to = "invalid.syntax[" } | Parsing HCL Traversal | (specific HCL error)           | # Invalid 'to' traversal

  Scenario: `moved` block with quoted string references (deprecated but parsed with warning)
    Given a configuration file containing:
      """
      moved {
        from = "test_instance.old_quoted" # WARNING: Quoted references are deprecated
        to   = "test_instance.new_quoted" # WARNING: Quoted references are deprecated
      }
      """
    When the configuration is parsed
    Then the `moved` block should be successfully parsed with `from` as "test_instance.old_quoted" and `to` as "test_instance.new_quoted"
    And 2 "Quoted references are deprecated" warnings should be reported
```
