# Auto-generated by Jules forterraform-enterprise-data team
# Based on logic in internal/configs/named_values.go (decodeOutputBlock)

Feature: Specific `output` Block Parsing Rules

  This feature describes specific parsing rules for `output {}` blocks,
  including name validation, handling of `precondition` blocks, and the
  rejection of `postcondition` blocks.

  Scenario Outline: Invalid `output` name
    Given a configuration file with an `output` block defined as:
      """
      output "<output_name>" {
        value = "test"
      }
      """
    When the configuration is parsed
    Then a diagnostic error with summary "Invalid output name" should be reported
    And its detail should contain "must be a valid identifier"

    Examples:
      | output_name    |
      | "123foo"       |
      | "foo-bar@!"    |
      | ""             | # Empty name, parser might catch earlier

  Scenario: `output` block with a valid `precondition` block
    Given a configuration file with:
      """
      resource "null_resource" "trigger" {}
      output "conditional_output" {
        value = "some value"
        precondition {
          condition     = length(null_resource.trigger.id) > 0 # Example condition
          error_message = "Trigger resource ID must exist."
        }
      }
      """
    When the configuration is parsed
    Then the "conditional_output" output block should be successfully parsed
    And it should contain one `precondition` block
    And that `precondition` block's condition should be "length(null_resource.trigger.id) > 0"
    And no critical parsing diagnostics should be reported for the precondition structure.

  Scenario: `output` block with a `postcondition` block (disallowed)
    Given a configuration file with:
      """
      output "output_with_postcondition" {
        value = "test value"
        postcondition { # Not allowed for outputs
          condition     = self == "test value"
          error_message = "Value must be 'test value'."
        }
      }
      """
    When the configuration is parsed
    Then a diagnostic error should be reported for the "output_with_postcondition" output block
    And its summary should be "Postconditions are not allowed"
    And its detail should contain "Output values can only have preconditions, not postconditions."

  Scenario: `output` block with `sensitive` and `ephemeral` attributes
    Given a configuration file with:
      """
      output "advanced_output" {
        value       = "very secret and temporary"
        sensitive   = true
        ephemeral   = true
        description = "An advanced output"
      }
      """
    When the configuration is parsed
    Then the "advanced_output" output block should be successfully parsed
    And its sensitive flag should be true
    And its ephemeral flag should be true
    And its description should be "An advanced output"
    And no critical parsing diagnostics should be reported.

  Scenario: `output` block missing required `value` attribute (schema validation)
    Given a configuration file with:
      """
      output "missing_value" {
        description = "This output has no value."
      }
      """
    When the configuration is parsed
    Then a diagnostic error should be reported for "missing_value"
    And its summary should be "Missing required argument"
    And its detail should contain "The argument \"value\" is required"
    # This is also covered in outputs_invalid.feature, but good to have here for completeness of decodeOutputBlock.
```
