# Auto-generated by Jules forterraform-enterprise-data team
# Based on an understanding of how the parser handles configuration directories,
# as indicated by tests in internal/configs/parser_config_dir_test.go.

Feature: Directory-Level Parsing of Output Blocks

  This feature describes how Terraform's parser handles output block definitions
  when loading an entire configuration directory, including interactions between
  multiple files, override files, and JSON configuration files.

  Scenario: Duplicate output definition across multiple .tf files
    Given a directory "test_module" with a file "outputs_a.tf" containing:
      """
      output "shared_output" {
        value = "defined in outputs_a.tf"
      }
      """
    And the same directory "test_module" also has a file "outputs_b.tf" containing:
      """
      output "shared_output" {
        value = "redefined in outputs_b.tf"
      }
      """
    When the parser loads the configuration directory "test_module"
    Then a diagnostic error should be reported indicating a duplicate "output" configuration block named "shared_output"

  Scenario: Output attributes overridden by an _override.tf file
    Given a directory "override_module" with a file "main.tf" containing:
      """
      output "overridden_output" {
        value       = "initial value"
        description = "Initial description"
        sensitive   = false
      }
      """
    And the same directory "override_module" also has a file "main_override.tf" containing:
      """
      output "overridden_output" {
        description = "Overridden description"
        sensitive   = true
      }
      """
    When the parser loads the configuration directory "override_module"
    Then the "overridden_output" output block should have its "value" attribute as "initial value"
    And its "description" attribute should be "Overridden description"
    And its "sensitive" attribute should be true
    And no diagnostic errors related to the override itself should be reported

  Scenario: Output defined in a .tf.json file
    Given a directory "json_module" with a file "outputs.tf.json" containing:
      """
      {
        "output": {
          "json_defined_output": {
            "value": "This output was defined in JSON",
            "description": "A JSON output example",
            "sensitive": true,
            "depends_on": ["some.resource"]
          },
          "another_json_output": {
            "value": 12345
          }
        }
      }
      """
    When the parser loads the configuration directory "json_module"
    Then the "json_defined_output" output block should be considered valid
    And its "value" attribute should be "This output was defined in JSON"
    And its "description" attribute should be "A JSON output example"
    And its "sensitive" attribute should be true
    And its "depends_on" attribute should reference ["some.resource"]
    And the "another_json_output" output block should be considered valid
    And its "value" attribute should be 12345
    And no diagnostic errors should be reported for these output definitions

  Scenario: Output defined in .tf and overridden by .tf.json override file
    Given a directory "json_override_module" with a file "main.tf" containing:
      """
      output "json_overridden_output" {
        value       = "tf value"
        description = "TF description"
      }
      """
    And the same directory "json_override_module" also has a file "override.tf.json" containing:
      """
      {
        "output": {
          "json_overridden_output": {
            "description": "JSON overridden description"
          }
        }
      }
      """
    When the parser loads the configuration directory "json_override_module"
    Then the "json_overridden_output" output block should have its "value" attribute as "tf value"
    And its "description" attribute should be "JSON overridden description"
    And no diagnostic errors related to the override should be reported

  Scenario: Missing value in output defined across multiple files (main and override)
    Given a directory "missing_value_split_module" with a file "main.tf" containing:
      """
      output "split_output_missing_value" {
        description = "Description in main.tf"
      }
      """
    And the same directory "missing_value_split_module" also has a file "override.tf" containing:
      """
      output "split_output_missing_value" {
        sensitive = true
      }
      """
    When the parser loads the configuration directory "missing_value_split_module"
    Then a diagnostic error should be reported indicating the missing "value" attribute for "split_output_missing_value"
```
