# Auto-generated by Jules forterraform-enterprise-data team
# Based on HCL2 schema for output blocks and common error patterns.
# Implicitly covered by TestParserLoadConfigFileFailure/TestParserLoadConfigFileFailureMessages
# in internal/configs/parser_config_test.go when such invalid files are present.

Feature: Invalid Output Block Definitions

  This feature describes various invalid syntax and attribute configurations
  for output blocks in Terraform, which should result in parsing errors.

  Scenario: Output block missing the required 'value' attribute
    Given a Terraform configuration file with the following content:
      """
      output "missing_value_output" {
        description = "This output is missing its value."
        sensitive   = false
      }
      """
    When the configuration is parsed
    Then a diagnostic error should be reported indicating the missing "value" attribute for "missing_value_output"
    # Exact error message might vary, e.g., "Missing required argument", "The argument "value" is required"

  Scenario: Output block with an unsupported attribute
    Given a Terraform configuration file with the following content:
      """
      output "unsupported_attr_output" {
        value         = "some value"
        invalid_attr  = "this should not be here"
        description   = "An output with an extra attribute."
      }
      """
    When the configuration is parsed
    Then a diagnostic error should be reported for "unsupported_attr_output" indicating an "Unsupported argument" named "invalid_attr"

  Scenario: Output block with 'sensitive' attribute of an incorrect type (string instead of boolean)
    Given a Terraform configuration file with the following content:
      """
      output "bad_sensitive_type_output" {
        value       = "sensitive value"
        sensitive   = "yes" # Should be a boolean
        description = "Output with wrong type for sensitive."
      }
      """
    When the configuration is parsed
    Then a diagnostic error should be reported for "bad_sensitive_type_output" indicating an "Unsuitable value type" for argument "sensitive" (expecting a bool)

  Scenario: Output block with 'depends_on' attribute of an incorrect type (string instead of list)
    Given a Terraform configuration file with the following content:
      """
      output "bad_depends_on_type_output" {
        value       = "dependent value"
        depends_on  = "another_resource.id" # Should be a list of traversals
        description = "Output with wrong type for depends_on."
      }
      """
    When the configuration is parsed
    Then a diagnostic error should be reported for "bad_depends_on_type_output" indicating an "Unsuitable value type" for argument "depends_on" (expecting a list or tuple)

  Scenario: Output block with 'description' attribute of an incorrect type (boolean instead of string)
    Given a Terraform configuration file with the following content:
      """
      output "bad_description_type_output" {
        value       = "described value"
        description = true # Should be a string
      }
      """
    When the configuration is parsed
    Then a diagnostic error should be reported for "bad_description_type_output" indicating an "Unsuitable value type" for argument "description" (expecting a string)

  Scenario: Duplicate output blocks with the same name
    Given a Terraform configuration file with the following content:
      """
      output "duplicate_name" {
        value = "first definition"
      }

      output "duplicate_name" {
        value = "second definition"
      }
      """
    When the configuration is parsed
    Then a diagnostic error should be reported indicating a duplicate "output" configuration block named "duplicate_name"

  Scenario: Output block with an invalid name (e.g., containing interpolation)
    Given a Terraform configuration file with the following content:
      """
      output "output_with_${var.name_part}" {
        value = "This name is invalid."
      }
      variable "name_part" { type = string , default = "interpolated"}
      """
    When the configuration is parsed
    Then a diagnostic error should be reported indicating an invalid block definition label or that labels cannot contain interpolations.
    # Exact error: "Invalid block definition label" or similar, pointing to the interpolated name.

  Scenario: Output block with 'value' attribute assigned an invalid expression (e.g., direct reference to a resource type)
    Given a Terraform configuration file with the following content:
      """
      resource "null_resource" "example" {}

      output "invalid_value_expression" {
        value = null_resource # Referencing the type, not an instance or attribute
      }
      """
    When the configuration is parsed
    Then a diagnostic error should be reported for "invalid_value_expression" indicating an invalid expression for "value" (e.g., "Reference to a resource type is not allowed")
```
