# Auto-generated by Jules forterraform-enterprise-data team
# Covers examples in internal/configs/testdata/valid-files/outputs.tf
# Implicitly tested by TestParserLoadConfigFileSuccess in internal/configs/parser_config_test.go

Feature: Valid Output Block Definitions

  This feature describes the valid syntax and attributes for defining outputs
  in Terraform configuration. Outputs declare values that will be displayed
  to the user when Terraform applies the configuration, and can be queried
  by other Terraform configurations.

  Scenario Outline: Defining various valid output blocks
    Given a Terraform configuration file containing an output block named "<output_name>"
    When the configuration is parsed
    Then the output block should be considered valid
    And its "<attribute>" should be correctly interpreted with value "<value>"
    And if "<attribute2>" is not empty, its "<attribute2>" should be correctly interpreted with value "<value2>"
    And if "<attribute3>" is not empty, its "<attribute3>" should be correctly interpreted with value "<value3>"

    Examples:
      | output_name  | attribute   | value          | attribute2   | value2            | attribute3   | value3         |
      | foo          | value       | "hello"        |              |                   |              |                |
      | bar          | value       | local.bar      |              |                   |              |                |
      | baz          | value       | "ssshhhhhhh"   | sensitive    | true              |              |                |
      | cheeze_pizza | description | "Nothing special" | value        | "🍕"             |              |                |
      | π            | value       | 3.14159265359  | depends_on   | ["pizza.cheese"]  |              |                |

  Scenario: Output block with only a value attribute
    Given a Terraform configuration file with the following content:
      """
      output "simple_output" {
        value = "This is a simple output."
      }
      """
    When the configuration is parsed
    Then the "simple_output" output block should be considered valid
    And its "value" attribute should be "This is a simple output."

  Scenario: Output block with a value and description
    Given a Terraform configuration file with the following content:
      """
      output "described_output" {
        value       = "This output has a description."
        description = "A brief explanation of what this output represents."
      }
      """
    When the configuration is parsed
    Then the "described_output" output block should be considered valid
    And its "value" attribute should be "This output has a description."
    And its "description" attribute should be "A brief explanation of what this output represents."

  Scenario: Output block marked as sensitive
    Given a Terraform configuration file with the following content:
      """
      output "secret_output" {
        value       = "This is a secret value."
        sensitive   = true
        description = "This output contains sensitive information."
      }
      """
    When the configuration is parsed
    Then the "secret_output" output block should be considered valid
    And its "value" attribute should be "This is a secret value."
    And its "sensitive" attribute should be true
    And its "description" attribute should be "This output contains sensitive information."

  Scenario: Output block with depends_on attribute
    Given a Terraform configuration file with the following content:
      """
      # Assume some resource or module named 'another_resource' exists
      resource "null_resource" "another_resource" {}

      output "dependent_output" {
        value       = "This output depends on another_resource."
        depends_on  = [null_resource.another_resource]
        description = "This output's value might be indirectly influenced by another_resource."
      }
      """
    When the configuration is parsed
    Then the "dependent_output" output block should be considered valid
    And its "value" attribute should be "This output depends on another_resource."
    And its "depends_on" attribute should reference ["null_resource.another_resource"]
    And its "description" attribute should be "This output's value might be indirectly influenced by another_resource."

  Scenario: Output block with a name containing special characters (e.g., Unicode)
    Given a Terraform configuration file with the following content:
      """
      output "你好世界" { # Hello World in Chinese
        value = "Output with Unicode name"
      }
      """
    When the configuration is parsed
    Then the "你好世界" output block should be considered valid
    And its "value" attribute should be "Output with Unicode name"

  Scenario: Output block with various value types
    Given a Terraform configuration file with the following content:
      """
      output "string_val" { value = "a string" }
      output "number_val" { value = 123.456 }
      output "bool_val"   { value = true }
      output "list_val"   { value = [1, "two", false] }
      output "map_val"    { value = { key1 = "val1", key2 = 100 } }
      """
    When the configuration is parsed
    Then the "string_val" output block's value should be "a string"
    And the "number_val" output block's value should be 123.456
    And the "bool_val" output block's value should be true
    And the "list_val" output block's value should be [1, "two", false]
    And the "map_val" output block's value should be { key1 = "val1", key2 = 100 }
```
