# Auto-generated by Jules forterraform-enterprise-data team
# Based on logic in internal/configs/parser.go (LoadHCLFile)

Feature: Parser File Loading Fundamentals

  This feature describes the basic file loading capabilities of the Terraform
  parser, including handling non-existent files and distinguishing between
  HCL native syntax (.tf) and HCL JSON syntax (.tf.json).

  Scenario: Attempting to load a non-existent configuration file
    Given a file path "non_existent_file.tf" that does not exist on the filesystem
    When the parser attempts to load the HCL file at "non_existent_file.tf"
    Then a diagnostic error should be reported with summary "Failed to read file"
    And its detail should contain "The file \"non_existent_file.tf\" could not be read."

  Scenario: Attempting to load a non-existent JSON configuration file
    Given a file path "non_existent_file.tf.json" that does not exist on the filesystem
    When the parser attempts to load the HCL file at "non_existent_file.tf.json"
    Then a diagnostic error should be reported with summary "Failed to read file"
    And its detail should contain "The file \"non_existent_file.tf.json\" could not be read."

  Scenario: Loading a valid HCL native syntax file (.tf)
    Given a file "valid.tf" with HCL native content:
      """
      resource "null_resource" "example" {}
      """
    When the parser loads the HCL file "valid.tf"
    Then the file should be parsed successfully as HCL native syntax
    And no "Failed to read file" or HCL parsing errors should be reported.

  Scenario: Loading a valid HCL JSON syntax file (.tf.json)
    Given a file "valid.tf.json" with HCL JSON content:
      """
      {
        "resource": {
          "null_resource": {
            "example": {}
          }
        }
      }
      """
    When the parser loads the HCL file "valid.tf.json"
    Then the file should be parsed successfully as HCL JSON syntax
    And no "Failed to read file" or JSON parsing errors should be reported.

  Scenario: Loading a .tf file containing JSON syntax (syntax mismatch)
    Given a file "mismatch.tf" with HCL JSON content:
      """
      {
        "variable": { "foo": { "type": "string" } }
      }
      """
    When the parser loads the HCL file "mismatch.tf"
    Then an HCL parsing diagnostic error should be reported (e.g., "Unexpected token", "Argument or block definition required")
    # Specific error message depends on HCL parser's recovery for JSON as HCL.

  Scenario: Loading a .tf.json file containing HCL native syntax (syntax mismatch)
    Given a file "mismatch.tf.json" with HCL native content:
      """
      variable "foo" { type = string }
      """
    When the parser loads the HCL file "mismatch.tf.json"
    Then an HCL JSON parsing diagnostic error should be reported (e.g., "Expected the start of an object or array")
    # Specific error message depends on HCL JSON parser.
```
