# Auto-generated by Jules forterraform-enterprise-data team
# Based on logic in internal/configs/parser_config_dir.go

Feature: Directory Parsing - Test, Query, and Mock Data File Loading

  This feature describes how `LoadConfigDir` handles the discovery and loading
  of special file types like test files (.tftest.hcl, .tftest.json),
  query files (.tfquery.hcl), and how `LoadMockDataDir` handles mock data
  files (.tfmock.hcl, .tfmock.json).

  Scenario: Loading a directory with primary configs and test files in a specified subdirectory
    Given a directory "module_with_tests" containing:
      - "main.tf" with content: `resource "null_resource" "main" {}`
      - "tests/standard_test.tftest.hcl" with content: `run "my_run" { command = plan }`
      - "tests/another.tftest.json" with content: `{ "run": { "json_run": { "command": "plan" } } }`
      - "tests/ignored.txt" with content: `some text`
    When `LoadConfigDir` is called for "module_with_tests" with test file matching in "tests/"
    Then the resulting Module should contain the "null_resource" "main"
    And the Module's `Tests` map should contain 2 entries
    And an entry for "tests/standard_test.tftest.hcl" should exist with a run block "my_run"
    And an entry for "tests/another.tftest.json" should exist with a run block "json_run"
    And no errors related to test file loading should be reported.

  Scenario: Loading a directory with test files when no test matching option is provided
    Given a directory "module_with_unmatched_tests" containing:
      - "main.tf" with content: `resource "null_resource" "main" {}`
      - "tests/standard_test.tftest.hcl" with content: `run "my_run" { command = plan }`
    When `LoadConfigDir` is called for "module_with_unmatched_tests" without test file matching
    Then the resulting Module should contain the "null_resource" "main"
    And the Module's `Tests` map should be empty
    And no errors should be reported.

  Scenario: Loading a directory with query files
    Given a directory "module_with_queries" containing:
      - "main.tf" with content: `variable "foo" { default = "bar" }`
      - "query_instances.tfquery.hcl" with content: `list "aws_instance" "all" { provider = aws }`
    When `LoadConfigDir` is called for "module_with_queries"
    Then the resulting Module should contain variable "foo"
    And the Module should contain one "list_resource" of type "aws_instance" named "all"
    And no errors related to query file loading should be reported.

  Scenario: Loading mock data files from a directory with `LoadMockDataDir`
    Given a directory "mock_data_set" containing:
      - "set1.tfmock.hcl" with content: `mock_resource "aws_instance" { default = { ami = "ami-123" } }`
      - "set2.tfmock.json" with content: `{ "mock_data_source": { "aws_caller_identity": { "default": { "account_id": "111" } } } }`
      - "override_set1.tfmock.hcl" with content: `mock_resource "aws_instance" { default = { ami = "ami-override" } }` # This will collide if merge is strict
    When `LoadMockDataDir` is called for "mock_data_set" with `useForPlanDefault=true` and strict merging (report collisions)
    Then the resulting MockData should contain a mock_resource "aws_instance" with default ami "ami-123" (or "ami-override" depending on load order and merge strategy if not strict)
    And it should contain a mock_data_source "aws_caller_identity" with default account_id "111"
    And if strict merging is applied and files are processed in order (set1, set2, override_set1), a diagnostic for duplicate "aws_instance" mock_resource should be reported by the merge.
    # Note: LoadMockDataDir itself calls LoadMockDataFile then MockData.Merge. The merge behavior (overwrite vs error on collision) is key.
    # The example assumes LoadMockDataDir's internal merge is set to not overwrite for this scenario to test collision diagnostics from Merge.

  Scenario: Loading mock data files with `LoadMockDataDir` and merge with overwrite
    Given a directory "mock_data_set_overwrite" containing:
      - "base.tfmock.hcl" with content: `mock_resource "my_res" { default = { attr = "base" } }`
      - "override.tfmock.hcl" with content: `mock_resource "my_res" { default = { attr = "override" } }`
    When `LoadMockDataDir` is called for "mock_data_set_overwrite" and its internal MockData.Merge allows overwrites (as if `overwrite=true` was passed to Merge)
    Then the resulting MockData should contain a mock_resource "my_res"
    And its default attribute "attr" should be "override" (assuming override.tfmock.hcl is processed after base.tfmock.hcl)
    And no collision diagnostics should be reported by the merge.

  Scenario: `LoadMockDataDir` for a non-existent directory
    Given a directory path "non_existent_mock_dir" that does not exist
    When `LoadMockDataDir` is called for "non_existent_mock_dir"
    Then a diagnostic error with summary "Failed to read mock data directory" should be reported.
```
