# Auto-generated by Jules forterraform-enterprise-data team
# Based on logic in internal/configs/parser_file_matcher.go

Feature: Configuration File Discovery and Categorization

  This feature describes how the Terraform parser discovers and categorizes
  different types of configuration files (.tf, .tf.json, override files,
  test files, query files) within a module directory.

  Background:
    Given a module directory path for parsing

  Scenario Outline: Identifying primary and override Terraform files
    Given the module directory contains a file named "<filename>"
    When the directory's files are categorized
    Then the file "<filename>" should be categorized as <expected_category>

    Examples:
      | filename              | expected_category |
      | "main.tf"             | Primary           |
      | "variables.tf"        | Primary           |
      | "outputs.tf.json"     | Primary           |
      | "resources.tf.json"   | Primary           |
      | "override.tf"         | Override          |
      | "prod_override.tf"    | Override          |
      | "override.tf.json"    | Override          |
      | "dev_override.tf.json"| Override          |
      | "my_config.tf"        | Primary           | # Not matching override pattern
      | "my_override_file.tf" | Primary           | # Suffix is not just "_override"

  Scenario: Loading test files from a specified test directory
    Given the module directory "my_module/"
    And "my_module/main.tf" exists
    And "my_module/tests/test_one.tftest.hcl" exists
    And "my_module/tests/test_two.tftest.json" exists
    And "my_module/tests/not_a_test.txt" exists
    When the parser categorizes files for "my_module/" with test file matching in "tests/"
    Then the identified test files should include "my_module/tests/test_one.tftest.hcl"
    And the identified test files should include "my_module/tests/test_two.tftest.json"
    And "my_module/tests/not_a_test.txt" should not be in the test files list
    And no critical errors should be reported.

  Scenario: Specified test directory does not exist (non-default)
    Given the module directory "my_module/"
    And "my_module/main.tf" exists
    And the directory "my_module/non_existent_tests/" does not exist
    When the parser categorizes files for "my_module/" with test file matching in "non_existent_tests/"
    Then a warning diagnostic should be reported with summary "Test directory does not exist"
    And its detail should contain "Requested test directory my_module/non_existent_tests does not exist."
    And the list of identified test files should be empty.

  Scenario: Default test directory ("tests/") does not exist
    Given the module directory "my_module/"
    And "my_module/main.tf" exists
    And the directory "my_module/tests/" does not exist
    When the parser categorizes files for "my_module/" with test file matching in the default "tests/" directory
    Then no "Test directory does not exist" warning should be reported (as it's the default and might not exist)
    And the list of identified test files should be empty.

  Scenario: Specified test directory exists but is unreadable
    Given the module directory "my_module/"
    And "my_module/main.tf" exists
    And the directory "my_module/unreadable_tests/" exists but is unreadable
    When the parser categorizes files for "my_module/" with test file matching in "unreadable_tests/"
    Then an error diagnostic should be reported with summary "Failed to read test directory"
    And its detail should contain "Test directory my_module/unreadable_tests could not be read".

  Scenario: Identifying query files when experiments are allowed
    Given the module directory contains "query_vpcs.tfquery.hcl" and "query_instances.tfquery.json"
    And language experiments are allowed for the parser
    When the directory's files are categorized
    Then the identified query files should include "query_vpcs.tfquery.hcl"
    And the identified query files should include "query_instances.tfquery.json"

  Scenario: Query files are not identified as query type when experiments are not allowed
    Given the module directory contains "query_vpcs.tfquery.hcl"
    And language experiments are NOT allowed for the parser
    When the directory's files are categorized
    Then "query_vpcs.tfquery.hcl" should not be categorized as a Query file
    # It might be categorized as Primary if it otherwise looks like a .tf/.tf.json file, or ignored.
    # The key is that the queryFiles matcher isn't active.

  Scenario: Main module directory is unreadable
    Given the module directory path "unreadable_dir/" points to an unreadable directory
    When the parser attempts to categorize files for "unreadable_dir/"
    Then an error diagnostic should be reported with summary "Failed to read module directory"
    And its detail should contain "Module directory unreadable_dir/ does not exist or cannot be read."

  Scenario: Files explicitly ignored by IsIgnoredFile are skipped by rootFiles scanner
    Given the module directory contains:
      - "main.tf"
      - ".temp.tf" (hidden file)
      - "backup.tf~" (vim backup)
      - "#swap.tf#" (emacs backup)
    When the directory's files are categorized by `rootFiles` (internal step of `dirFileSet`)
    Then "main.tf" should be considered for categorization (e.g. as Primary)
    And ".temp.tf" should be ignored
    And "backup.tf~" should be ignored
    And "#swap.tf#" should be ignored
```
