# Auto-generated by Jules forterraform-enterprise-data team
# Based on logic in internal/configs/parser_config.go (parseConfigFile)

Feature: Configuration File Parsing Orchestration

  This feature describes how the Terraform parser (`parseConfigFile`)
  orchestrates the decoding of various top-level configuration blocks and
  blocks within the `terraform {}` block, dispatching to specific decoders.
  It also covers structural rules enforced at this level.

  Scenario Outline: Recognition of valid top-level configuration blocks
    Given a configuration file "test.tf" containing a single top-level block:
      """
      <block_hcl>
      """
    When the configuration file is parsed
    Then the file should be parsed successfully
    And the parsed File object should contain one <expected_block_collection> of type/name "<expected_block_key>"
    And no critical parsing errors related to block type recognition should occur.

    Examples:
      | block_hcl                                    | expected_block_collection | expected_block_key |
      | variable "my_var" { type = string }          | Variables                 | my_var             |
      | output "my_out" { value = "hello" }         | Outputs                   | my_out             |
      | locals { my_local = "val" }                  | Locals                    | my_local           | # Note: Locals are stored by name directly
      | resource "null_resource" "my_res" {}         | ManagedResources          | null_resource.my_res |
      | data "null_data_source" "my_data" {}         | DataResources             | null_data_source.my_data |
      | module "my_mod" { source = "./child" }       | ModuleCalls               | my_mod             |
      | provider "aws" { region = "us-east-1" }      | ProviderConfigs           | aws                |
      | moved { from = res.a, to = res.b }           | Moved                     | (entry in list)    | # Moved are list items
      | import { to = res.a, id = "id" }             | Import                    | (entry in list)    | # Imports are list items
      | check "my_check" { assert {c=true,e="m"} }   | Checks                    | my_check           |
      | action "custom" "my_action" {}               | Actions                   | custom.my_action   | # Assuming experiment enabled
      | ephemeral "custom" "my_eph" {}               | EphemeralResources        | custom.my_eph      | # Assuming experiment enabled

  Scenario Outline: Recognition of valid blocks within a `terraform {}` block
    Given a configuration file "test.tf" containing:
      """
      terraform {
        <nested_block_hcl>
      }
      """
    When the configuration file is parsed
    Then the file should be parsed successfully
    And the parsed File object's `terraform` block content should reflect the presence of "<nested_block_type>"
    And no critical parsing errors related to block type recognition within `terraform {}` should occur.

    Examples:
      | nested_block_hcl                                      | nested_block_type    |
      | backend "local" { path = "state.tfstate" }            | backend              |
      | cloud { organization = "my-org" }                     | cloud                |
      | required_providers { aws = { source = "h/aws" } }     | required_providers   |
      | provider_meta "aws" { data_source_schema_addrs_only_for_dynamic_types = true } | provider_meta "aws"  |
      # state_store would require experiment to be active

  Scenario: `required_providers` block incorrectly placed at the top level
    Given a configuration file "test.tf" containing:
      """
      required_providers { # Should be inside terraform {}
        myprovider = {
          source = "example.com/org/myprovider"
        }
      }
      """
    When the configuration file is parsed
    Then a diagnostic error should be reported
    And its summary should be "Invalid required_providers block"
    And its detail should contain "A \"required_providers\" block must be nested inside a \"terraform\" block."

  Scenario: Initial sniffing of `required_version` and `experiments`
    Given a configuration file "test.tf" containing:
      """
      terraform {
        required_version = "~> 1.0"
        experiments      = [my_exp] # Assuming my_exp is valid & experiments allowed
      }
      resource "null_resource" "example" {} # A regular block
      """
    When the configuration file is parsed by `parseConfigFile`
    Then the `CoreVersionConstraints` should be sniffed and set to "~> 1.0" before other blocks are fully decoded
    And the `ActiveExperiments` should include "my_exp" before other blocks are fully decoded
    And the "null_resource" "example" should also be parsed.

  Scenario: `LoadConfigFileOverride` correctly sets the `override` flag for decoders
    Given a configuration file "override_test.tf" intended as an override file, containing:
      """
      variable "my_var" { description = "Overridden description" }
      # Assume "my_var" is defined in a base file for a valid override scenario
      """
    When the parser loads "override_test.tf" using `LoadConfigFileOverride`
    Then the `decodeVariableBlock` function should be called with its `override` parameter set to true for "my_var"
    # This ensures that override-specific logic within decode*Block functions is triggered.
    # The functional outcome of the override is tested in module_file_processing.feature & module_merge_specifics.feature.
```
