# Auto-generated by Jules forterraform-enterprise-data team
# Based on logic in internal/configs/parser_config_dir.go

Feature: Directory Utility Functions for Parsing

  This feature describes utility functions related to directory parsing,
  such as identifying ignored files and determining if a directory is empty
  or contains Terraform configurations.

  Scenario Outline: Identifying ignored files
    Given a filename "<filename>"
    When it is checked if the file should be ignored
    Then the result should be <should_be_ignored>

    Examples:
      | filename          | should_be_ignored |
      | "main.tf"         | false             |
      | ".main.tf.swp"    | true              | # Unix-like hidden file / swap
      | "main.tf~"        | true              | # Vim backup
      | "#main.tf#"       | true              | # Emacs backup
      | "_override.tf"    | false             |
      | ".git"            | true              |
      | "foo.bar"         | false             |
      | "terraform.tfstate" | false             | # State files are not ignored at this level

  Scenario Outline: Checking if a directory is a config directory (`IsConfigDir`)
    Given a directory structure:
      | File Path                | Content (if relevant) |
      | <file1_path>             | <file1_content>       |
      | <file2_path>             | <file2_content>       |
      # Use "N/A" if file path/content is not applicable for the scenario
    When checking if "<target_dir>" is a Terraform config directory (ignoring tests/queries for this check)
    Then the result should be <is_config_dir>

    Examples:
      | target_dir   | file1_path           | file1_content        | file2_path | file2_content | is_config_dir |
      | "empty_dir"  | "N/A"                | "N/A"                | "N/A"      | "N/A"         | false         |
      | "has_tf"     | "has_tf/main.tf"     | "resource null_resource a {}" | "N/A"      | "N/A"         | true          |
      | "has_tfjson" | "has_tfjson/vars.tf.json" | "{}"                 | "N/A"      | "N/A"         | true          |
      | "has_both"   | "has_both/main.tf"   | ""                   | "has_both/vars.tf.json" | "{}"        | true          |
      | "only_ignored"| "only_ignored/.swp"| "swap"               | "N/A"      | "N/A"         | false         |
      | "only_readme"| "only_readme/README.md"| "docs"             | "N/A"      | "N/A"         | false         |
      | "only_tests" | "only_tests/tests/main.tftest.hcl" | ""     | "N/A"      | "N/A"         | false         | # IsConfigDir doesn't count tests

  Scenario Outline: Checking if a directory is empty of relevant files (`IsEmptyDir`)
    # IsEmptyDir checks for .tf, .tf.json, AND test files
    Given a directory structure:
      | File Path                | Content (if relevant) |
      | <file1_path>             | <file1_content>       |
      | <file2_path>             | <file2_content>       |
    And the test file directory pattern is "<test_dir_pattern>" (e.g., "tests" or "")
    When checking if "<target_dir>" is empty of Terraform config and test files
    Then the result should be <is_empty>

    Examples:
      | target_dir   | test_dir_pattern | file1_path           | file1_content        | file2_path | file2_content | is_empty |
      | "empty_dir"  | "tests"          | "N/A"                | "N/A"                | "N/A"      | "N/A"         | true     |
      | "has_tf"     | "tests"          | "has_tf/main.tf"     | "resource null_resource a {}" | "N/A"      | "N/A"         | false    |
      | "only_readme"| "tests"          | "only_readme/README.md"| "docs"             | "N/A"      | "N/A"         | true     |
      | "only_tests_match" | "tests"    | "only_tests_match/tests/main.tftest.hcl" | "" | "N/A"      | "N/A"         | false    |
      | "only_tests_nomatch" | "other"  | "only_tests_nomatch/tests/main.tftest.hcl" | "" | "N/A"      | "N/A"         | true     | # Test dir pattern doesn't match
      | "tf_and_tests" | "tests"        | "tf_and_tests/main.tf" | ""                 | "tf_and_tests/tests/a.tftest.hcl" | "" | false  |
```
