# Auto-generated by Jules forterraform-enterprise-data team
# Based on logic in internal/configs/provider_meta.go
# and examples in internal/configs/testdata/valid-modules/provider-meta/

Feature: Parsing `provider_meta` Blocks

  This feature describes how Terraform parses `provider_meta {}` blocks,
  which are nested within `terraform {}` blocks. These are used for
  provider-specific meta-arguments that influence Terraform's behavior.

  Scenario: Valid `provider_meta` block with static attributes
    Given a configuration file containing:
      """
      terraform {
        provider_meta "myprovider" {
          static_string_arg = "hello"
          static_bool_arg   = true
          static_number_arg = 123
        }
      }
      """
    When the configuration is parsed
    Then a `provider_meta` block for "myprovider" should be successfully parsed
    And its config body should contain attribute "static_string_arg" with value "hello"
    And its config body should contain attribute "static_bool_arg" with value true
    And its config body should contain attribute "static_number_arg" with value 123
    And no critical parsing diagnostics should be reported.

  Scenario: Invalid provider name in `provider_meta` label (contains alias)
    Given a configuration file containing:
      """
      terraform {
        provider_meta "myprovider.aliased" { # Alias not allowed in label
          some_arg = "value"
        }
      }
      """
    When the configuration is parsed
    Then a diagnostic error should be reported for the `provider_meta` block
    And its summary should be "Invalid provider name"
    And its detail should contain "Provider name cannot include an alias." (or similar from checkProviderNameNormalized)

  Scenario: Non-static value (variable reference) in `provider_meta` attribute
    Given a configuration file containing:
      """
      variable "dynamic_val" { type = string, default = "some_value" }

      terraform {
        provider_meta "myprovider" {
          dynamic_arg = var.dynamic_val # Not allowed, must be static
        }
      }
      """
    When the configuration is parsed
    Then a diagnostic error should be reported for the `provider_meta` "myprovider"
    And its summary should be "Invalid expression" or "Variables not allowed" for attribute "dynamic_arg"
    And its detail should indicate that the expression must not refer to variables or resources.

  Scenario: Non-static value (resource reference) in `provider_meta` attribute
    Given a configuration file containing:
      """
      resource "null_resource" "example" {}

      terraform {
        provider_meta "myprovider" {
          dynamic_arg = null_resource.example.id # Not allowed, must be static
        }
      }
      """
    When the configuration is parsed
    Then a diagnostic error should be reported for the `provider_meta` "myprovider"
    And its summary should be "Invalid expression" or "Resource references not allowed" for attribute "dynamic_arg"
    And its detail should indicate that the expression must not refer to variables or resources.

  Scenario: Nested block inside `provider_meta` (disallowed)
    Given a configuration file containing:
      """
      terraform {
        provider_meta "myprovider" {
          nested_block {} # Not allowed, only attributes
        }
      }
      """
    When the configuration is parsed
    Then a diagnostic error should be reported for the `provider_meta` "myprovider"
    And its summary should be "Extraneous nested_block block" or "Blocks are not allowed here"
    And its detail should indicate that only attributes are permitted.

  Scenario: `provider_meta` block missing required provider name label
    Given a configuration file containing:
      """
      terraform {
        provider_meta { # Missing provider name label
          some_arg = "value"
        }
      }
      """
    When the configuration is parsed
    Then a diagnostic error should be reported (likely by the HCL parser itself)
    And its summary should indicate "Missing provider name label for provider_meta block" or similar.
```
