# Auto-generated by Jules forterraform-enterprise-data team
# Based on logic in internal/configs/provider_validation.go

Feature: Structural Provider Configuration Validation Across Modules

  This feature describes how Terraform validates provider configurations
  structurally across module boundaries, including restrictions when module
  calls use meta-arguments like count/for_each/depends_on, and how
  `required_providers` declarations are handled.

  Scenario: Module call with `count` prevents provider blocks in child module
    Given a root module with:
      """
      module "child_with_provider" {
        source = "./child"
        count  = 2
      }
      """
    And a child module "./child" with:
      """
      provider "aws" {
        region = "us-east-1" # Child attempts to define its own provider
      }
      resource "aws_instance" "example" {}
      """
    When the configuration is validated for provider configurations
    Then an error diagnostic should be reported with summary "Module is incompatible with count, for_each, and depends_on"
    And its detail should mention that the module at "./child" contains local provider configurations.
    And the diagnostic subject should point to the `count = 2` line in the root module.

  Scenario: Module call with `for_each` prevents provider blocks in child module
    Given a root module with:
      """
      module "child_with_provider" {
        source   = "./child"
        for_each = toset(["a", "b"])
      }
      """
    And a child module "./child" with:
      """
      provider "aws" {
        region = "us-east-1"
      }
      """
    When the configuration is validated for provider configurations
    Then an error diagnostic should be reported with summary "Module is incompatible with count, for_each, and depends_on"
    And its subject should point to the `for_each` line in the root module.

  Scenario: Module call with `depends_on` prevents provider blocks in child module
    Given a root module with:
      """
      resource "null_resource" "trigger" {}
      module "child_with_provider" {
        source     = "./child"
        depends_on = [null_resource.trigger]
      }
      """
    And a child module "./child" with:
      """
      provider "aws" {
        region = "us-east-1"
      }
      """
    When the configuration is validated for provider configurations
    Then an error diagnostic should be reported with summary "Module is incompatible with count, for_each, and depends_on"
    And its subject should point to the `depends_on` line in the root module.

  Scenario: Duplicate `required_provider` for the same FQN under different local names
    Given a module configuration with:
      """
      terraform {
        required_providers {
          aws_main = { # First local name
            source  = "hashicorp/aws"
            version = "~> 4.0"
          }
          aws_alternate = { # Second local name for the same source
            source  = "hashicorp/aws"
            version = "~> 4.1"
          }
        }
      }
      """
    When the configuration is validated for provider configurations
    Then a warning diagnostic should be reported with summary "Duplicate required provider"
    And its detail should state 'Provider "registry.terraform.io/hashicorp/aws" with the local name "aws_alternate" was previously required as "aws_main".' (or similar)
    And the diagnostic subject should point to the `aws_alternate` block.

  Scenario: Implied provider name from resource mismatches `required_providers` local name for the same FQN
    Given a module configuration with:
      """
      terraform {
        required_providers {
          # User chose 'my_custom_aws_name' for the standard AWS provider
          my_custom_aws_name = {
            source  = "hashicorp/aws"
            version = "~> 4.0"
          }
        }
      }
      # This resource implies provider "aws", which is hashicorp/aws,
      # but required_providers uses "my_custom_aws_name" for it.
      resource "aws_instance" "example" {
        ami           = "ami-123"
        instance_type = "t2.micro"
      }
      """
    When the configuration is validated for provider configurations
    Then a warning diagnostic should be reported with summary "Duplicate required provider"
    And its detail should contain 'Provider "registry.terraform.io/hashicorp/aws" was implicitly required via resource "aws_instance.example", but listed in required_providers as "my_custom_aws_name".'
    And its detail should suggest 'Either the local name in required_providers must match the resource name, or the "my_custom_aws_name" provider must be assigned within the resource block.'
    And the diagnostic subject should point to the `resource "aws_instance" "example"` block.

  Scenario: Valid implied provider name matching default part of FQN in `required_providers`
    Given a module configuration with:
      """
      terraform {
        required_providers {
          aws = { # Local name 'aws' matches implied provider for aws_instance
            source  = "hashicorp/aws"
            version = "~> 4.0"
          }
        }
      }
      resource "aws_instance" "example" {
        ami           = "ami-123"
        instance_type = "t2.micro"
      }
      """
    When the configuration is validated for provider configurations
    Then no "Duplicate required provider" warning related to "aws_instance.example" and "aws" local name should be reported.
```
