# Auto-generated by Jules forterraform-enterprise-data team
# Covers tests in internal/configs/provider_test.go (TestProviderReservedNames)
# Uses testdata/invalid-files/provider-reserved.tf

Feature: Reserved Names in Provider Configuration Blocks

  This feature describes how Terraform handles the use of reserved argument
  names and block type names within provider configuration blocks. Using such
  names should result in diagnostics indicating that these names are reserved
  for future use by Terraform.

  Scenario: Using reserved arguments and block types in a provider block
    Given a configuration file "config.tf" with the following content:
      """
      provider "aws" {
        alias   = "testing"
        version = "~> 3.0" # Deprecated location for version constraint

        # Reserved arguments
        count      = 1
        depends_on = []
        for_each   = {}
        source     = "hashicorp/aws" # Reserved argument name

        # Reserved block types
        lifecycle {}
        locals {}
      }
      """
    When the configuration file "config.tf" is parsed
    Then the following diagnostics should be reported (order may vary):
      | Severity | Summary                                          | Detail                                                                                                                                                                                                                            | File      | Line | Col |
      | Warning  | Version constraints inside provider configuration blocks are deprecated | Terraform 0.13 and earlier allowed provider version constraints inside the provider configuration block, but that is now deprecated and will be removed in a future version of Terraform. To silence this warning, move the provider version constraint into the required_providers block. | config.tf | 4    | 13  |
      | Error    | Reserved argument name in provider block         | The provider argument name "count" is reserved for use by Terraform in a future version.                                                                                                                                          | config.tf | 10   | 3   |
      | Error    | Reserved argument name in provider block         | The provider argument name "depends_on" is reserved for use by Terraform in a future version.                                                                                                                                     | config.tf | 11   | 3   |
      | Error    | Reserved argument name in provider block         | The provider argument name "for_each" is reserved for use by Terraform in a future version.                                                                                                                                       | config.tf | 12   | 3   |
      | Error    | Reserved argument name in provider block         | The provider argument name "source" is reserved for use by Terraform in a future version.                                                                                                                                         | config.tf | 13   | 3   |
      | Error    | Reserved block type name in provider block       | The block type name "lifecycle" is reserved for use by Terraform in a future version.                                                                                                                                             | config.tf | 14   | 3   |
      | Error    | Reserved block type name in provider block       | The block type name "locals" is reserved for use by Terraform in a future version.                                                                                                                                                | config.tf | 15   | 3   |
```
