# Auto-generated by Jules forterraform-enterprise-data team
# Based on logic in internal/configs/provider_validation.go

Feature: Provider Configuration Validation for Module Calls

  This feature describes how Terraform validates the `providers` meta-argument
  in `module` blocks, ensuring that provider configurations are correctly
  passed from parent to child modules and that types match.

  Background:
    Given a root module (parent) configuration
    And a child module "./child" configuration

  Scenario: Parent module call passes an undefined provider configuration to child
    Given the root module contains:
      """
      module "child_consumer" {
        source = "./child"
        providers = {
          # 'undefined_in_parent' is not defined in root's provider/required_providers
          aws = undefined_in_parent
        }
      }
      """
    And the child module "./child" contains:
      """
      terraform {
        required_providers {
          aws = { source = "hashicorp/aws" }
        }
      }
      resource "aws_instance" "example" {}
      """
    When the configuration is validated for provider configurations
    Then a warning diagnostic should be reported with summary "Reference to undefined provider"
    And its detail should state 'There is no explicit declaration for local provider name "undefined_in_parent" in the root module, so Terraform is assuming you mean to pass a configuration for provider "registry.terraform.io/hashicorp/undefined_in_parent".'
    And its detail should suggest adding a `required_providers` entry for "undefined_in_parent" in the root module.
    And the diagnostic subject should point to the `aws = undefined_in_parent` line in the module call.

  Scenario: Child module does not declare requirement for a provider passed by parent
    Given the root module contains:
      """
      provider "aws" { region = "us-east-1" }
      module "child_no_need" {
        source = "./child"
        providers = {
          # Child does not have 'special_aws' in its required_providers
          special_aws = aws
        }
      }
      """
    And the child module "./child" contains:
      """
      # No required_providers for 'special_aws' or default 'aws'
      resource "null_resource" "example" {} # Does not use aws
      """
    When the configuration is validated for provider configurations
    Then a diagnostic error (or warning, depending on if child_special_aws is default type) should be reported with summary "Reference to undefined provider" for the child module
    And its detail should state 'The child module does not declare any provider requirement with the local name "special_aws".' (or similar for default if applicable)
    And the diagnostic subject should point to the `special_aws = aws` line in the module call.

  Scenario: Provider type mismatch between parent and child in module call
    Given the root module contains:
      """
      provider "aws"    { alias = "parent_aws"; region = "us-east-1" }
      provider "google" { alias = "parent_gcp"; project = "my-proj" }

      module "type_mismatch_child" {
        source = "./child"
        providers = {
          # Child expects 'aws_provider', parent passes a 'google' provider config
          aws_provider = google.parent_gcp
        }
      }
      """
    And the child module "./child" contains:
      """
      terraform {
        required_providers {
          aws_provider = { source = "hashicorp/aws" }
        }
      }
      resource "aws_instance" "example" {
        provider = aws_provider
      }
      """
    When the configuration is validated for provider configurations
    Then an error diagnostic should be reported with summary "Provider type mismatch"
    And its detail should state 'The local name "google.parent_gcp" in the root module represents provider "registry.terraform.io/hashicorp/google", but "aws_provider" in module.type_mismatch_child represents "registry.terraform.io/hashicorp/aws".' (or similar)
    And the diagnostic subject should point to `google.parent_gcp` in the module call.

  Scenario: Child module defines its own provider, parent attempts to override via `providers`
    Given the root module contains:
      """
      provider "aws" { alias = "parent_config"; region = "us-east-1" }
      module "self_sufficient_child" {
        source = "./child"
        providers = {
          # Attempting to pass 'aws' when child defines its own 'aws'
          aws = aws.parent_config
        }
      }
      """
    And the child module "./child" contains:
      """
      provider "aws" { # Child defines its own default 'aws'
        region = "us-west-2"
      }
      resource "aws_instance" "example" {}
      """
    When the configuration is validated for provider configurations
    Then an error diagnostic should be reported with summary "Cannot override provider configuration"
    And its detail should state 'The configuration of module.self_sufficient_child has its own local configuration for aws, and so it cannot accept an overridden configuration provided by the root module.'
    And the diagnostic subject should point to `aws = aws.parent_config` in the module call.

  Scenario: Child module requires an aliased provider, parent does not provide it
    Given the root module contains:
      """
      provider "aws" { region = "us-east-1" } # Default aws
      module "needy_child" {
        source = "./child"
        # Missing providers = { "aws.special_one" = aws }
      }
      """
    And the child module "./child" contains:
      """
      terraform {
        required_providers {
          aws = {
            source = "hashicorp/aws"
            configuration_aliases = [ aws.special_one ]
          }
        }
      }
      resource "aws_instance" "example" {
        provider = aws.special_one
      }
      """
    When the configuration is validated for provider configurations
    Then an error diagnostic should be reported with summary "Missing required provider configuration"
    And its detail should state 'The child module requires an additional configuration for provider "registry.terraform.io/hashicorp/aws", with the local name "aws.special_one".'
    And its detail should suggest adding an entry for "aws.special_one" to the "providers" meta-argument.
    And the diagnostic subject should point to the `module "needy_child"` block.

  Scenario: Deprecated empty provider block in child module (proxy provider)
    Given the root module contains:
      """
      provider "aws" { region = "us-east-1" }
      module "legacy_child" {
        source = "./child"
        # Parent implicitly passes its default 'aws'
      }
      """
    And the child module "./child" contains:
      """
      provider "aws" {} # Empty "proxy" provider block
      resource "aws_instance" "example" {}
      """
    When the configuration is validated for provider configurations
    Then a warning diagnostic should be reported with summary "Redundant empty provider block"
    And its detail should suggest migrating to `required_providers` with `configuration_aliases` if needed.
    And the diagnostic subject should point to the empty `provider "aws"` block in the child module.
```
