# Auto-generated by Jules forterraform-enterprise-data team
# Covers tests in internal/configs/provider_test.go (TestParseProviderConfigCompact and TestParseProviderConfigCompactStr)

Feature: Parsing Compact Provider Configuration Strings

  This feature describes how Terraform parses compact provider configuration
  strings (often used in resource `provider` arguments or import blocks)
  into a structured local provider configuration address.

  Scenario Outline: Valid compact provider configuration strings
    Given a compact provider configuration string "<input_string>"
    When the string is parsed as a compact provider configuration
    Then the resulting local provider configuration should have local name "<expected_local_name>"
    And if "<expected_alias>" is not empty, its alias should be "<expected_alias>"
    And no parsing diagnostics should be reported

    Examples:
      | input_string | expected_local_name | expected_alias |
      | aws          | aws                 |                |
      | google       | google              |                |
      | aws.foo      | aws                 | foo            |
      | mycloud.bar  | mycloud             | bar            |
      | ns/name      | ns/name             |                | # Assuming local names can contain slashes if not aliased
      | ns/name.alias| ns/name             | alias          |


  Scenario Outline: Invalid compact provider configuration strings
    Given a compact provider configuration string "<input_string>"
    When the string is parsed as a compact provider configuration
    Then a diagnostic error should be reported with the detail "<expected_error_detail>"

    Examples:
      | input_string | expected_error_detail                                                                              |
      | aws["foo"]   | The provider type name must either stand alone or be followed by an alias name separated with a dot. |
      | .alia        | Provider type name is required.                                                                    |
      | provider.    | Provider alias is required after the dot.                                                          |
      | provider.123 | Provider alias must be a valid identifier.                                                         |
      | ""           | Provider type name is required.                                                                    |
```
