# Auto-generated by Jules forterraform-enterprise-data team
# Covers tests in internal/configs/provider_requirements_test.go (TestDecodeRequiredProvidersBlock)

Feature: Parsing `required_providers` Blocks

  This feature describes how Terraform parses `required_providers` blocks
  within a `terraform` configuration block. It covers various formats for
  specifying provider requirements, including source addresses, version
  constraints, and local names, as well as error handling for invalid
  configurations.

  Scenario Outline: Parsing valid `required_providers` entries
    Given a `required_providers` block with the following HCL content for entry "<local_name>":
      """
      <hcl_content>
      """
    When the `required_providers` block is decoded
    Then the entry for local name "<local_name>" should be valid
    And its FQN should be "<expected_fqn>"
    And its source string should be "<expected_source_string>"
    And its version constraint should be "<expected_version_constraint>"
    And no parsing diagnostics should be reported for this entry

    Examples:
      | local_name | hcl_content                                            | expected_fqn                         | expected_source_string | expected_version_constraint |
      | default    | default = "1.0.0"                                      | default.host/-/default               |                        | 1.0.0                       | # Legacy format
      | my-test    | my-test = { source = "mycloud/test", version = "2.0.0" } | default.host/mycloud/test            | mycloud/test           | 2.0.0                       | # Modern format with source
      | another    | another = { version = "~>3.0" }                        | default.host/-/another               |                        | ~>3.0                       | # Modern format, version only (implies default source)
      | public     | public = { source = "hashicorp/aws", version = ">= 3.0" } | default.host/hashicorp/aws         | hashicorp/aws          | >= 3.0                      |
      | custom     | custom = { source = "myregistry.com/ns/type", version = "1.1.0" } | myregistry.com/ns/type           | myregistry.com/ns/type | 1.1.0                       | # Fully qualified source

  Scenario: Parsing a `required_providers` block with mixed valid entries
    Given a `required_providers` block with the following HCL content:
      """
      legacy  = "1.0.0"
      my-test = {
        source  = "mycloud/test"
        version = "2.0.0"
      }
      other = {
        version = "~> 1.5"
      }
      """
    When the `required_providers` block is decoded
    Then the entry for local name "legacy" should have FQN "default.host/-/legacy" and version "1.0.0"
    And the entry for local name "my-test" should have FQN "default.host/mycloud/test", source "mycloud/test", and version "2.0.0"
    And the entry for local name "other" should have FQN "default.host/-/other" and version "~> 1.5"
    And no parsing diagnostics should be reported for these entries

  Scenario Outline: Parsing invalid `required_providers` entries
    Given a `required_providers` block with the following HCL content for entry "<local_name>":
      """
      <hcl_content>
      """
    When the `required_providers` block is decoded
    Then a diagnostic error should be reported for the entry "<local_name>" with summary "<expected_error_summary>"

    Examples:
      | local_name | hcl_content                                                               | expected_error_summary              |
      | my-test    | my-test = { source = "some/invalid/provider/source/test", version = "~>2.0.0" } | Invalid provider source string      |
      | my_test    | my_test = { version = "~>2.0.0" }                                         | Invalid provider local name         | # Underscore in name
      | MYTEST     | MYTEST  = { version = "~>2.0.0" }                                         | Invalid provider local name         | # Uppercase in name
      | my-test    | my-test = { source = "mycloud/test", version = "invalid" }                | Invalid version constraint          |
      | test       | test    = ["2.0.0"]                                                       | Invalid required_providers object   | # Value is a list, not string or object
      | my-test    | my-test = { source = null }                                               | Invalid source                      | # Source is not a string
      | my-test    | my-test = { source = "mycloud/test", version = "2.0.0", invalid = true }  | Invalid required_providers object   | # Additional unknown attribute "invalid"
      | no-value   | no-value = {}                                                             | Invalid required_providers object   | # Missing version or source
      | bad-source | bad-source = { source = 123, version = "1.0.0" }                          | Invalid source                      | # Source is not a string

  Scenario: Parsing a `required_providers` block with multiple invalid entries
    Given a `required_providers` block with the following HCL content:
      """
      valid-entry = { source = "hashicorp/ok", version = "1.0" }
      bad_name    = { version = "1.0" }
      bad-version = { source = "hashicorp/err", version = "not-semver" }
      """
    When the `required_providers` block is decoded
    Then a diagnostic error with summary "Invalid provider local name" should be reported for entry "bad_name"
    And a diagnostic error with summary "Invalid version constraint" should be reported for entry "bad-version"
    And the entry for "valid-entry" should be parsed correctly
```
