# Auto-generated by Jules forterraform-enterprise-data team
# Based on logic in internal/configs/provisioner.go and relevant test files.

Feature: Parsing `provisioner` Blocks within Resources

  This feature describes how Terraform parses `provisioner {}` blocks defined
  within resources, including validation of type, meta-arguments (`when`,
  `on_failure`), nested `connection` blocks, and reference restrictions for
  destroy-time provisioners.

  Scenario Outline: Valid provisioner definition
    Given a resource block containing a provisioner defined as:
      """
      provisioner "<type>" {
        <attributes_and_blocks>
      }
      """
    When the configuration is parsed
    Then a provisioner of type "<type>" should be successfully parsed
    And its `when` condition should be <expected_when>
    And its `on_failure` behavior should be <expected_on_failure>
    And if a connection block is defined as <connection_block_hcl>, it should be parsed
    And no critical parsing diagnostics should be reported for this provisioner.

    Examples:
      | type         | attributes_and_blocks                                      | expected_when | expected_on_failure | connection_block_hcl      |
      | "local-exec" | command = "echo hello"                                     | Create        | Fail                |                           |
      | "local-exec" | command = "cleanup" \n when = "destroy"                    | Destroy       | Fail                |                           |
      | "remote-exec"| inline = ["ls"] \n on_failure = "continue"                 | Create        | Continue            | connection { host="a"}    |
      | "file"       | source = "a.txt" \n destination = "/b.txt" \n _ { foo="bar" } | Create        | Fail                |                           | # With escaping block

  Scenario Outline: Using removed provisioner types
    Given a resource block containing: `provisioner "<removed_type>" {}`
    When the configuration is parsed
    Then a diagnostic error should be reported with summary 'The "<removed_type>" provisioner has been removed'
    And its detail should mention deprecation and removal.

    Examples:
      | removed_type      |
      | "chef"            |
      | "habitat"         |
      | "puppet"          |
      | "salt-masterless" |

  Scenario Outline: Invalid keyword for `when` or `on_failure`
    Given a resource block containing: `provisioner "local-exec" { <attribute> = "<invalid_keyword>" }`
    When the configuration is parsed
    Then a diagnostic error should be reported with summary 'Invalid "<attribute_name>" keyword'
    And its detail should list the allowed keywords for "<attribute_name>".

    Examples:
      | attribute    | attribute_name | invalid_keyword |
      | when         | when           | "always"        |
      | when         | when           | "update"        |
      | on_failure   | on_failure     | "ignore"        |
      | on_failure   | on_failure     | "retry"         |

  Scenario Outline: Invalid references in destroy-time provisioners or their connection blocks
    Given a resource "null_resource" "example" containing a provisioner:
      """
      provisioner "local-exec" {
        when    = destroy
        # Connection block defined by <connection_block_hcl> if present
        # Command defined by <command_expr> if present
        <provisioner_content>
      }
      """
    When the configuration is parsed
    Then a diagnostic error with summary "Invalid reference from destroy provisioner" should be reported.

    Examples:
      | provisioner_content                                     |
      | command = var.some_var                                  | # var reference in command
      | connection { host = local.some_local }                  | # local reference in connection
      | command = other_resource.id                             | # other resource reference in command
      | connection { user = data.aws_caller_identity.current.arn } | # data source reference in connection

  Scenario: Valid references in destroy-time provisioners
    Given a resource "null_resource" "example" containing a provisioner:
      """
      provisioner "local-exec" {
        when    = destroy
        command = "echo ${self.id} ${count.index} ${each.key} ${path.module} ${terraform.workspace}"
        connection {
          host = self.id # Valid self reference
        }
      }
      """
    When the configuration is parsed
    Then no "Invalid reference from destroy provisioner" errors should be reported for these specific references.

  Scenario: Duplicate `connection` blocks in a provisioner
    Given a resource block containing:
      """
      provisioner "remote-exec" {
        inline = ["echo hello"]
        connection { host = "host1" }
        connection { host = "host2" } # Duplicate
      }
      """
    When the configuration is parsed
    Then a diagnostic error with summary "Duplicate connection block" should be reported.

  Scenario: Duplicate escaping `_` blocks in a provisioner
    Given a resource block containing:
      """
      provisioner "local-exec" {
        command = "echo base"
        _ { escaped_arg1 = "val1" }
        _ { escaped_arg2 = "val2" } # Duplicate
      }
      """
    When the configuration is parsed
    Then a diagnostic error with summary "Duplicate escaping block" should be reported.

  Scenario: Reserved block type (e.g., "lifecycle") used inside a provisioner
    Given a resource block containing:
      """
      provisioner "local-exec" {
        command = "echo hello"
        lifecycle {} # Reserved, not allowed here
      }
      """
    When the configuration is parsed
    Then a diagnostic error with summary "Reserved block type name in provisioner block" should be reported for "lifecycle".
```
