# Auto-generated by Jules forterraform-enterprise-data team
# Based on logic in internal/configs/query_file.go and related test files.

Feature: Parsing Query Files (.tfquery.hcl)

  This feature describes how Terraform parses query files, which are used for
  an experimental resource querying feature. It focuses on the structure of
  these files and the `list {}` blocks within them. Query files are typically
  only parsed if language experiments are enabled.

  Scenario: Valid query file with multiple `list` blocks and other allowed blocks
    Given a query file "my_queries.tfquery.hcl" with content:
      """
      variable "region_filter" {
        type    = string
        default = "us-east-1"
      }

      locals {
        common_tags = {
          Environment = "dev"
        }
      }

      provider "aws" {
        # Query files can have their own provider configs if needed for the query context
        region = var.region_filter
      }

      list "aws_vpc" "all_dev_vpcs" {
        provider = aws # Refers to the provider block above
        config {
          tags = local.common_tags
        }
      }

      list "aws_instance" "specific_instances" {
        provider         = aws
        include_resource = true
        limit            = 10
        config {
          instance_type = "t2.micro"
          tags = {
            Name = "web-server-${count.index}" # Example, assuming count might be used
          }
        }
        count = 2
      }
      """
    And language experiments are allowed
    When the query file "my_queries.tfquery.hcl" is parsed
    Then the parsed QueryFile object should contain 1 variable definition named "region_filter"
    And it should contain 1 local value definition named "common_tags"
    And it should contain 1 provider configuration for "aws"
    And it should contain a "list" resource of type "aws_vpc" named "all_dev_vpcs"
    And the "all_dev_vpcs" list resource should reference provider "aws"
    And its nested config should contain attribute "tags"
    And it should contain a "list" resource of type "aws_instance" named "specific_instances"
    And the "specific_instances" list resource should reference provider "aws"
    And its "include_resource" attribute should be true (as an expression)
    And its "limit" attribute should be 10 (as an expression)
    And its "count" attribute should be 2 (as an expression)
    And no critical parsing diagnostics should be reported.

  Scenario Outline: Invalid block type in a query file
    Given a query file "invalid_blocks.tfquery.hcl" with content:
      """
      <block_hcl> # e.g., resource "null_resource" "foo" {}
      """
    And language experiments are allowed
    When the query file "invalid_blocks.tfquery.hcl" is parsed
    Then a diagnostic error with summary "Invalid block type" should be reported
    And its detail should contain "This block type is not valid within a query file: <block_type_name>"

    Examples:
      | block_hcl                              | block_type_name |
      | resource "null_resource" "foo" {}      | resource        |
      | output "bar" { value = "baz" }         | output          |
      | module "qux" { source = "./qux" }      | module          |
      | terraform { required_version = "1.0" } | terraform       |

  Scenario: Duplicate `list` block names in a query file
    Given a query file "duplicate_lists.tfquery.hcl" with content:
      """
      list "aws_instance" "my_instances" {
        provider = aws
      }
      list "aws_instance" "my_instances" { # Duplicate type and name
        provider = aws
      }
      """
    And language experiments are allowed
    When the query file "duplicate_lists.tfquery.hcl" is parsed
    Then a diagnostic error with summary "Duplicate \"list\" block names" should be reported
    And its detail should contain 'This query file already has a list block named aws_instance.my_instances defined at' (referring to the first one).

  Scenario: `list` block missing the required `provider` attribute
    Given a query file "missing_provider.tfquery.hcl" with content:
      """
      list "aws_instance" "web_servers" {
        # provider attribute is missing
        config {
          tags = { Name = "web" }
        }
      }
      """
    And language experiments are allowed
    When the query file "missing_provider.tfquery.hcl" is parsed
    Then a diagnostic error with summary "Missing \"provider\" attribute" should be reported
    And its detail should be "You must specify a provider attribute when defining a list block."

  Scenario Outline: Invalid name for a `list` block
    Given a query file "invalid_list_name.tfquery.hcl" with content:
      """
      list "aws_instance" "<list_name>" { provider = aws }
      """
    And language experiments are allowed
    When the query file "invalid_list_name.tfquery.hcl" is parsed
    Then a diagnostic error with summary "Invalid list block name" should be reported
    And its detail should contain "must be a valid identifier"

    Examples:
      | list_name     |
      | "123servers"  |
      | "web-servers@!"|

  Scenario: `list` block with both `count` and `for_each`
    Given a query file "count_foreach.tfquery.hcl" with content:
      """
      list "aws_instance" "conflict" {
        provider = aws
        count    = 2
        for_each = toset(["a", "b"])
      }
      """
    And language experiments are allowed
    When the query file "count_foreach.tfquery.hcl" is parsed
    Then a diagnostic error with summary 'Invalid combination of "count" and "for_each"' should be reported.

  Scenario: `list` block with multiple nested `config` blocks (if validated as error)
    Given a query file "multi_config.tfquery.hcl" with content:
      """
      list "aws_instance" "multi_conf" {
        provider = aws
        config { key = "val1" }
        config { key = "val2" } # Second config block
      }
      """
    And language experiments are allowed
    When the query file "multi_config.tfquery.hcl" is parsed
    Then a diagnostic error with summary "Duplicate config block" should be reported (if this check is active in decodeQueryListBlock)
    And its detail should state "A list block must contain only one nested \"config\" block."
    # The Go code for decodeQueryListBlock has a loop that seems to check for this.
```
