# Auto-generated by Jules forterraform-enterprise-data team
# Based on logic in internal/configs/removed.go

Feature: Parsing `removed` Blocks for State Refactoring

  This feature describes how Terraform parses `removed {}` blocks, which are
  used to specify resources or modules that have been removed from the
  configuration, often as part of a refactoring workflow.

  Scenario Outline: Valid `removed` block definitions
    Given a configuration file containing a `removed` block:
      """
      removed {
        from = <from_address>
        <optional_blocks>
      }
      """
    And any referenced resources (e.g. for provisioner self context) are syntactically valid
    When the configuration is parsed
    Then the `removed` block should be successfully parsed
    And its `from` target should be "<from_address_str>"
    And its `destroy` flag should be <expected_destroy_flag>
    And if "<num_provisioners>" is not "0", it should have <num_provisioners> provisioner(s)
    And if "<has_connection>" is "true", it should have a connection block defined
    And no critical parsing diagnostics should be reported for this `removed` block.

    Examples:
      | from_address              | optional_blocks                                                                                                | from_address_str          | expected_destroy_flag | num_provisioners | has_connection |
      | aws_instance.old          | # No optional blocks                                                                                           | aws_instance.old          | true                  | 0                | false          |
      | aws_instance.old_no_destroy | lifecycle { destroy = false }                                                                                  | aws_instance.old_no_destroy | false                 | 0                | false          |
      | aws_instance.with_conn    | connection { user = "admin" }                                                                                  | aws_instance.with_conn    | true                  | 0                | true           |
      | aws_instance.with_prov    | provisioner "local-exec" { command = "echo done", when = destroy }                                             | aws_instance.with_prov    | true                  | 1                | false          |
      | aws_instance.full         | lifecycle { destroy = true } \n connection { host = self.private_ip } \n provisioner "local-exec" { when=destroy, command="echo ${self.id}" } | aws_instance.full         | true                  | 1                | true           |
      | data.aws_ami.old          | # No optional blocks, data sources cannot have them                                                            | data.aws_ami.old          | true                  | 0                | false          |
      | module.old_module         | # No optional blocks, modules cannot have them                                                                 | module.old_module         | true                  | 0                | false          |

  Scenario Outline: Invalid `removed` block definitions
    Given a configuration file containing a `removed` block:
      """
      <removed_block_hcl>
      """
    When the configuration is parsed
    Then a diagnostic error with summary "<expected_error_summary>" should be reported
    And if "<expected_error_detail_fragment>" is not empty, its detail should contain "<expected_error_detail_fragment>"

    Examples:
      | removed_block_hcl                                                                 | expected_error_summary        | expected_error_detail_fragment |
      | removed { to = aws_instance.foo }                                                 | Missing required argument     | from                           | # Missing 'from'
      | removed { from = "invalid.[syntax" }                                             | Parsing HCL Traversal         | (HCL error details)            |
      | removed { from = data.foo.bar; connection {} }                                    | Invalid connection block      | valid only when a removed block targets a managed resource |
      | removed { from = module.foo; provisioner "local-exec" { command="echo" } }        | Invalid provisioner block     | valid only when a removed block targets a managed resource |
      | removed { from = aws_instance.foo; connection {} connection {} }                  | Duplicate connection block    | already has a connection block |
      | removed { from = aws_instance.foo; provisioner "local-exec" { command="echo", when="create"} } | Invalid provisioner block     | Only destroy-time provisioners are valid |
      | removed { from = aws_instance.foo; lifecycle { create_before_destroy = true } }   | Unsupported argument          | create_before_destroy          | # Invalid attr in removed lifecycle

  Scenario: `removed` block with invalid traversal in `from` attribute
    Given a configuration file containing:
      """
      removed {
        from = aws_instance.old[?(@.name == "foo")] # Invalid HCL traversal syntax for this context
      }
      """
    When the configuration is parsed
    Then a diagnostic error should be reported for the `from` attribute
    And its summary should relate to "Parsing HCL Traversal" or "Invalid character"
```
