# Auto-generated by Jules forterraform-enterprise-data team
# Based on logic in internal/configs/resource.go and relevant test files.

Feature: Parsing `resource`, `data`, and `ephemeral` Blocks

  This feature describes how Terraform parses `resource "type" "name" {}`,
  `data "type" "name" {}`, and `ephemeral "type" "name" {}` blocks, including
  their common meta-arguments, lifecycle configurations, and specific
  restrictions.

  Scenario Outline: Valid resource, data, or ephemeral block with common meta-arguments
    Given a configuration file with a block:
      """
      <block_mode> "<type_name>" "<instance_name>" {
        <meta_args>
        # config_body attribute if any
      }
      """
    When the configuration is parsed
    Then a <block_mode_enum> resource of type "<type_name>" and name "<instance_name>" should be successfully parsed
    And its `count` expression should be "<count_expr>" if "<count_expr>" is not empty
    And its `for_each` expression should be "<for_each_expr>" if "<for_each_expr>" is not empty
    And its provider reference should be "<provider_ref>" if "<provider_ref>" is not empty
    And its `depends_on` references should include <depends_on_refs> if "<depends_on_refs>" is not empty
    And no critical parsing diagnostics should be reported for this block.

    Examples:
      | block_mode | block_mode_enum | type_name        | instance_name | meta_args                                       | count_expr | for_each_expr | provider_ref | depends_on_refs            |
      | resource   | ManagedResource | aws_instance     | web           | count = 2                                       | 2          |               |              |                            |
      | data       | DataResource    | aws_ami          | ubuntu        | for_each = toset(["a","b"])\n provider = aws.east |            | toset(["a","b"]) | aws.east     |                            |
      | resource   | ManagedResource | null_resource    | trigger       | depends_on = [aws_instance.web]                 |            |               |              | ["aws_instance.web"]       |
      | ephemeral  | EphemeralResource | local_file_gen | setup         | provider = localfiles                           |            |               | localfiles   |                            |

  Scenario Outline: Invalid resource, data, or ephemeral block labels
    Given a configuration file with a block: `<block_mode> "<type_label>" "<name_label>" {}`
    When the configuration is parsed
    Then a diagnostic error with summary "Invalid <block_mode> <label_issue_type> name" should be reported
    And its detail should contain "must be a valid identifier".

    Examples:
      | block_mode | type_label   | name_label   | label_issue_type |
      | resource   | "123type"    | "validname"  | type             |
      | resource   | "validtype"  | "123name"    | resource         |
      | data       | "aws-ami@!"  | "validname"  | data source      | # data source type is "name" in error
      | data       | "validtype"  | "aws-ami@!"  | data resource    |
      | ephemeral  | "bad type"   | "validname"  | ephemeral resource type |
      | ephemeral  | "validtype"  | "bad name"   | ephemeral resource name |

  Scenario: `resource` block with `count` and `for_each` (mutually exclusive)
    Given a configuration file with: `resource "null_resource" "conflict" { count = 1, for_each = {a=1} }`
    When the configuration is parsed
    Then a diagnostic error with summary 'Invalid combination of "count" and "for_each"' should be reported.

  Scenario: `resource` block with `lifecycle` arguments
    Given a configuration file with:
      """
      resource "aws_instance" "example" {
        lifecycle {
          create_before_destroy = true
          prevent_destroy       = false # Explicitly false
          ignore_changes        = [ "tags.Name", all ] # "all" takes precedence
          replace_triggered_by  = [ null_resource.trigger.id ]
        }
      }
      resource "null_resource" "trigger" {}
      """
    When the configuration is parsed
    Then the "aws_instance" "example" resource should have `CreateBeforeDestroy` as true
    And `PreventDestroy` as false (explicitly set)
    And `IgnoreAllChanges` should be true
    And its `IgnoreChanges` list should contain a traversal for "tags.Name" (though 'all' overrides)
    And its `TriggersReplacement` list should contain an expression for "null_resource.trigger.id".

  Scenario: `resource` block with invalid `ignore_changes = ["*"]`
    Given a configuration file with: `resource "null_resource" "legacy_ignore" { lifecycle { ignore_changes = ["*"] } }`
    When the configuration is parsed
    Then a diagnostic error with summary "Invalid ignore_changes wildcard" should be reported
    And its detail should state 'The ["*"] form of ignore_changes wildcard is was deprecated and is now invalid. Use "ignore_changes = all" to ignore changes to all attributes.'

  Scenario Outline: Invalid `replace_triggered_by` expressions in resource `lifecycle`
    Given a configuration file with: `resource "null_resource" "r" { lifecycle { replace_triggered_by = [<expression>] } }`
    And other necessary declarations like `variable "foo" {}` or `resource "other" "res" {}`
    When the configuration is parsed
    Then a diagnostic error with summary "<expected_summary>" should be reported for `replace_triggered_by`.

    Examples:
      | expression                   | expected_summary                             |
      | var.foo                      | Invalid reference in replace_triggered_by expression | # Variable ref not allowed
      | local.bar                    | Invalid reference in replace_triggered_by expression | # Local ref not allowed
      | other.res.id, other.res.name | Invalid replace_triggered_by expression      | # Multiple resource references in one expression string (parser might catch earlier as syntax error depending on how it's written)
      | each.value                   | Invalid each reference in replace_triggered_by expression | # Must be each.key
      | count.foo                    | Invalid count reference in replace_triggered_by expression | # Must be count.index
      | "string_literal"             | Invalid replace_triggered_by expression      | # Missing resource reference

  Scenario: Duplicate `lifecycle` or `connection` or `_` block in a resource
    Given a configuration file with:
      """
      resource "null_resource" "duplicates" {
        lifecycle {}
        lifecycle {} # Duplicate
        connection {}
        connection {} # Duplicate
        _ { foo = "bar" }
        _ { bar = "baz" } # Duplicate
      }
      """
    When the configuration is parsed
    Then a diagnostic error "Duplicate lifecycle block" should be reported
    And a diagnostic error "Duplicate connection block" should be reported
    And a diagnostic error "Duplicate escaping block" should be reported.

  Scenario: Reserved block type (e.g. "locals") directly in a `resource` block
    Given a configuration file with: `resource "null_resource" "reserved" { locals {} }`
    When the configuration is parsed
    Then a diagnostic error "Reserved block type name in resource block" for "locals" should be reported.

  Scenario Outline: Invalid `lifecycle` arguments for `data` or `ephemeral` resources
    Given a configuration file with: `<block_mode> "<type_name>" "<instance_name>" { lifecycle { <lifecycle_arg> = true } }`
    When the configuration is parsed
    Then a diagnostic error with summary "Invalid <block_mode> resource lifecycle argument" should be reported for "<lifecycle_arg>".

    Examples:
      | block_mode | type_name | instance_name | lifecycle_arg           |
      | data       | http      | example       | create_before_destroy   |
      | data       | http      | example       | prevent_destroy         |
      | data       | http      | example       | ignore_changes          | # Even 'all' or list
      | ephemeral  | custom    | temp          | create_before_destroy   |

  Scenario: `data` or `ephemeral` resource with valid `precondition`/`postcondition` in `lifecycle`
    Given a configuration file with:
      """
      data "http" "example" {
        lifecycle {
          precondition { condition = self.url != "", error_message = "URL must be set."}
        }
      }
      ephemeral "custom" "temp" {
        lifecycle {
          postcondition { condition = true, error_message = "Always true."} # Example, condition needs real check
        }
      }
      """
    When the configuration is parsed
    Then no errors related to the presence of `precondition` or `postcondition` in these blocks should be reported.

  Scenario: `data` block nested inside a `check` block cannot use `count` or `for_each`
    Given a configuration file with:
      """
      check "my_check" {
        data "external" "checker" {
          count   = 2 # Not allowed in nested data
          program = ["echo", "{\"status\":\"ok\"}"]
        }
        assert { condition = true, error_message = "m" }
      }
      """
    When the configuration is parsed
    Then a diagnostic error with summary 'Invalid "count" attribute' should be reported for the nested data block
    And its detail should state "meta-arguments are not supported within nested data blocks."
```
