# Auto-generated by Jules forterraform-enterprise-data team
# Based on logic in internal/configs/state_store.go

Feature: Parsing `state_store` Blocks (Experimental)

  This feature describes how Terraform parses `state_store "type" {}` blocks,
  which are part of an experimental pluggable state storage feature and are
  nested within `terraform {}` blocks. It focuses on the required nested
  `provider` block and its constraints.

  Background:
    Given a configuration file with a `terraform {}` block
    And language experiments allowing `state_store` are active

  Scenario: Valid `state_store` block with required nested provider
    Given the `terraform {}` block contains:
      """
      state_store "custom_s3" {
        # Main config for the state_store itself
        bucket = "my-tfstate-bucket"
        region = "us-west-2"

        provider "aws" { # Nested provider for the state_store's backend operations
          region = "us-west-2" # Provider-specific config
        }
      }
      """
    When the configuration is parsed
    Then a `state_store` of type "custom_s3" should be successfully parsed
    And it should contain a nested provider configuration of type "aws"
    And the `state_store`'s main config body should contain attribute "bucket"
    And no critical parsing diagnostics should be reported for the `state_store` structure.

  Scenario: `state_store` block missing the nested `provider` block
    Given the `terraform {}` block contains:
      """
      state_store "etcd_store" {
        endpoints = ["etcd1:2379"]
        # Missing nested provider block
      }
      """
    When the configuration is parsed
    Then a diagnostic error should be reported for the "etcd_store" `state_store` block
    And its summary should be "Missing provider block"
    And its detail should state "A 'provider' block is required in 'state_store' blocks".

  Scenario: `state_store` block with multiple nested `provider` blocks
    Given the `terraform {}` block contains:
      """
      state_store "multi_provider_store" {
        provider "aws" { region = "us-east-1" }
        provider "gcp" { project = "my-proj" } # Second provider block
      }
      """
    When the configuration is parsed
    Then a diagnostic error should be reported for the "multi_provider_store" `state_store` block
    And its summary should be "Duplicate provider block"
    And its detail should state "Only one 'provider' block should be present in a 'state_store' block".

  Scenario: Nested `provider` block within `state_store` has an alias (disallowed)
    Given the `terraform {}` block contains:
      """
      state_store "aliased_provider_store" {
        provider "aws.special" { # Alias "special" is not allowed here
          region = "us-east-1"
        }
      }
      """
    When the configuration is parsed
    Then a diagnostic error should be reported for the nested `provider` block
    And its summary should be "Unexpected provider alias"
    And its detail should state "Aliases are disallowed in the 'provider' block in the 'state_store' block".

  Scenario: `state_store` block with an invalid type label (e.g., containing a dot)
    Given the `terraform {}` block contains:
      """
      state_store "my.store" { # Type label should be a simple identifier
        provider "aws" {}
      }
      """
    When the configuration is parsed
    Then a diagnostic error should be reported for the `state_store` block's label
    And its summary should indicate an invalid label or that it cannot contain ".".
    # Note: This might be caught by the generic HCL label parser.

  Scenario: `state_store` block with unsupported top-level attributes or blocks
    Given the `terraform {}` block contains:
      """
      state_store "my_store" {
        unsupported_attr = "value" # Not part of schema, goes to main Config
        provider "aws" {}
        unsupported_block {} # Not 'provider'
      }
      """
    When the configuration is parsed
    Then the `state_store` "my_store" main config body should contain "unsupported_attr"
    And a diagnostic error should be reported for "unsupported_block"
    And its summary should be "Unsupported block" or similar, as only "provider" is defined in `StateStorageBlockSchema`.
```
