# Auto-generated by Jules forterraform-enterprise-data team
# Based on logic in internal/configs/named_values.go (decodeVariableBlock)
# and relevant files in internal/configs/testdata/

Feature: Parsing `variable` Blocks

  This feature describes how Terraform parses `variable {}` blocks, including
  validation of names, types, default values, sensitivity, nullability,
  and `validation` sub-blocks.

  Scenario Outline: Valid `variable` block definitions
    Given a configuration file with a `variable` block named "<var_name>" defined as:
      """
      <variable_hcl_content>
      """
    When the configuration is parsed
    Then the variable "<var_name>" should be successfully parsed
    And its description should be "<description>" if "<description>" is not empty
    And its type string should be "<type_string>"
    And its default value should be <default_value_cty> if "<default_value_cty>" is not "not set"
    And its sensitive flag should be <sensitive>
    And its ephemeral flag should be <ephemeral>
    And its nullable flag should be <nullable>
    And no critical parsing diagnostics should be reported for this variable block

    Examples:
      | var_name              | variable_hcl_content                                                                 | description        | type_string    | default_value_cty        | sensitive | ephemeral | nullable |
      | foo                   | variable "foo" {}                                                                    |                    | dynamic        | not set                  | false     | false     | true     | # Defaults: type=dynamic, nullable=true
      | bar                   | variable "bar" { default = "hello" }                                                 |                    | dynamic        | "hello"                  | false     | false     | true     |
      | baz                   | variable "baz" { type = list }                                                       |                    | list(any)      | not set                  | false     | false     | true     | # Shorthand list
      | map_var               | variable "map_var" { type = map }                                                      |                    | map(any)       | not set                  | false     | false     | true     | # Shorthand map
      | complex_type          | variable "complex_type" { type = object({ a=string, b=number }) }                    |                    | object({a:string,b:number}) | not set           | false     | false     | true     |
      | with_desc             | variable "with_desc" { description = "My test var" }                                 | "My test var"      | dynamic        | not set                  | false     | false     | true     |
      | sensitive_var         | variable "sensitive_var" { sensitive = true }                                        |                    | dynamic        | not set                  | true      | false     | true     |
      | ephemeral_var         | variable "ephemeral_var" { ephemeral = true }                                        |                    | dynamic        | not set                  | false     | true      | true     |
      | nullable_false        | variable "nullable_false" { type = string, nullable = false, default = "val" }       |                    | string         | "val"                    | false     | false     | false    |
      | nullable_true_null    | variable "nullable_true_null" { type = string, nullable = true, default = null }      |                    | string         | null                     | false     | false     | true     |
      | full_example          | variable "full_example" { description="d", type=number, default=1, sensitive=true, ephemeral=true, nullable=false } | "d"              | number         | 1                        | true      | true      | false    |

  Scenario Outline: Invalid `variable` name
    Given a configuration file with a `variable` block defined as:
      """
      variable "<var_name>" {}
      """
    When the configuration is parsed
    Then a diagnostic error with summary "Invalid variable name" should be reported
    And its detail should contain "<expected_detail_fragment>"

    Examples:
      | var_name       | expected_detail_fragment        |
      | "123foo"       | must be a valid identifier      |
      | "foo-bar@!"    | must be a valid identifier      |
      | "source"       | reserved due to its special meaning | # Reserved module block attribute
      | "providers"    | reserved due to its special meaning | # Reserved module block attribute

  Scenario Outline: Invalid `variable` type specification (legacy quoted)
    Given a configuration file with a `variable` block defined as:
      """
      variable "legacy_type_var" {
        type = "<legacy_type_str>"
      }
      """
    When the configuration is parsed
    Then a diagnostic error with summary "Invalid quoted type constraints" should be reported
    And its detail should contain "<expected_detail_fragment>"

    Examples:
      | legacy_type_str | expected_detail_fragment            |
      | "string"        | Remove the quotes around "string"   |
      | "list"          | Remove the quotes around "list"     |
      | "map"           | Remove the quotes around "map"      |

  Scenario: Invalid `variable` default value for its type
    Given a configuration file with:
      """
      variable "type_mismatch" {
        type    = number
        default = "not-a-number"
      }
      """
    When the configuration is parsed
    Then a diagnostic error with summary "Invalid default value for variable" should be reported for "type_mismatch"
    And its detail should contain "not compatible with the variable's type constraint"

  Scenario: Invalid `variable` default value (null when nullable is false)
    Given a configuration file with:
      """
      variable "non_nullable_null_default" {
        type     = string
        nullable = false
        default  = null
      }
      """
    When the configuration is parsed
    Then a diagnostic error with summary "Invalid default value for variable" should be reported for "non_nullable_null_default"
    And its detail should be "A null default value is not valid when nullable=false."

  Scenario Outline: Invalid type for boolean flags (`sensitive`, `ephemeral`, `nullable`)
    Given a configuration file with a `variable` "bad_flag_type" containing:
      """
      variable "bad_flag_type" {
        <attribute_name> = "not-a-boolean" # Should be a boolean
      }
      """
    When the configuration is parsed
    Then a diagnostic error should be reported for "bad_flag_type"
    And its summary should contain "Unsuitable value type" or "could not be decoded" for attribute "<attribute_name>"

    Examples:
      | attribute_name |
      | sensitive      |
      | ephemeral      |
      | nullable       |

  Scenario: `validation` block with condition not referencing the variable itself
    Given a configuration file with:
      """
      variable "validation_no_ref" {
        type = string
        validation {
          condition     = true # Does not reference var.validation_no_ref
          error_message = "Condition is static."
        }
      }
      """
    When the configuration is parsed
    Then a diagnostic error with summary "Invalid variable validation condition" should be reported for variable "validation_no_ref"
    And its detail should contain "must refer to var.validation_no_ref"

  Scenario: `validation` block with condition referencing the variable itself (valid)
    Given a configuration file with:
      """
      variable "validation_with_ref" {
        type = string
        validation {
          condition     = length(var.validation_with_ref) > 0
          error_message = "Cannot be empty."
        }
      }
      """
    When the configuration is parsed
    Then no "Invalid variable validation condition" error should be reported for variable "validation_with_ref".

  Scenario: Variable with object type using optional attributes and a default value
    Given a configuration file with:
      """
      variable "obj_optional_default" {
        type = object({
          req_attr = string
          opt_attr = optional(number, 123) # Optional with type default
        })
        default = {
          req_attr = "hello"
          # opt_attr is omitted, should use type default
        }
      }
      """
    When the configuration is parsed
    Then the variable "obj_optional_default" default value should effectively be `{ req_attr = "hello", opt_attr = 123 }`
    And no critical parsing diagnostics should be reported.

  Scenario: Variable with object type using optional attributes, default value provides null for optional
    Given a configuration file with:
      """
      variable "obj_optional_null_default" {
        type = object({
          req_attr = string
          opt_attr = optional(number) # Optional, no type default
        })
        default = {
          req_attr = "hello"
          opt_attr = null # Explicitly null in variable default
        }
        nullable = true # Assuming the overall variable can be null, though not directly relevant to opt_attr here
      }
      """
    When the configuration is parsed
    Then the variable "obj_optional_null_default" default value should effectively be `{ req_attr = "hello", opt_attr = null }`
    And no critical parsing diagnostics should be reported.
```
