# Auto-generated by Jules forterraform-enterprise-data team
# Covers tests in internal/configs/named_values_test.go

Feature: Variable Default Value Validation

  This feature describes how Terraform validates the default value of a variable
  against its specified type constraint.

  Scenario: Invalid default value for a variable with a complex type
    Given a configuration file "test.tf" with the following content:
      """
      variable "foo" {
        type = map(object({
          foo = bool
        }))

        default = {
          "thingy" = {
            foo = "string where bool is expected"
          }
        }
      }
      """
    When the configuration file "test.tf" is parsed
    Then at least one diagnostic error should be reported
    And one of the error diagnostics should have:
      | Summary                                | Detail                                                                                                |
      | Invalid default value for variable     | This default value is not compatible with the variable's type constraint: ["thingy"].foo: a bool is required. |
```
